# Generated by Django 5.2.12 on 2026-04-07 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('category', models.CharField(choices=[('resume', 'Resume'), ('invoice', 'Invoice'), ('card', 'Visiting Card'), ('social', 'Social Media Post')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('html_layout', models.TextField(help_text='Django template HTML with {{ variables }}')),
                ('css_layout', models.TextField(blank=True)),
                ('preview_image', models.ImageField(blank=True, null=True, upload_to='previews/')),
                ('sample_data', models.JSONField(default=dict, help_text='Demo data for example mode')),
                ('fields_schema', models.JSONField(default=list, help_text='List of {name,label,type} for dynamic forms')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('data', models.JSONField(default=dict)),
                ('rendered_html', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='generator.template')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
