# Generated by Django 5.2.12 on 2026-04-07 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='category',
            field=models.CharField(choices=[('resume', 'Resume'), ('invoice', 'Invoice'), ('card', 'Visiting Card'), ('social', 'Social Media Post'), ('wedding', 'Wedding Invitation')], max_length=20),
        ),
    ]
