# Generated by Django 5.2.12 on 2026-04-07 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0004_generateddocument_is_public_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template',
            name='category',
            field=models.CharField(choices=[('resume', 'Resume'), ('invoice', 'Invoice'), ('card', 'Visiting Card'), ('social', 'Social Media Post'), ('wedding', 'Wedding Invitation'), ('certificate', 'Certificate'), ('cover_letter', 'Cover Letter'), ('birthday', 'Birthday Invitation'), ('festival', 'Festival Card'), ('flyer', 'Flyer / Poster'), ('menu', 'Menu Card'), ('ticket', 'Event Ticket'), ('voucher', 'Gift Voucher')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='template',
            name='title',
            field=models.CharField(db_index=True, max_length=120),
        ),
    ]
