# Generated by Django 5.2.12 on 2026-04-07 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0005_alter_template_category_alter_template_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrandKit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(blank=True, max_length=100)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('logo', models.TextField(blank=True, help_text='Base64 data URL of logo image')),
                ('primary_color', models.CharField(default='#6366f1', max_length=20)),
                ('secondary_color', models.CharField(default='#a855f7', max_length=20)),
                ('accent_color', models.CharField(default='#ec4899', max_length=20)),
                ('text_color', models.CharField(default='#0f172a', max_length=20)),
                ('background_color', models.CharField(default='#ffffff', max_length=20)),
                ('heading_font', models.CharField(choices=[('Inter', 'Inter (Modern Sans)'), ('Playfair Display', 'Playfair Display (Elegant Serif)'), ('Cormorant Garamond', 'Cormorant Garamond (Classic Serif)'), ('Poppins', 'Poppins (Friendly Sans)'), ('Montserrat', 'Montserrat (Bold Sans)'), ('Roboto', 'Roboto (Clean Sans)'), ('Lora', 'Lora (Editorial Serif)'), ('Oswald', 'Oswald (Strong Display)')], default='Inter', max_length=60)),
                ('body_font', models.CharField(choices=[('Inter', 'Inter (Modern Sans)'), ('Playfair Display', 'Playfair Display (Elegant Serif)'), ('Cormorant Garamond', 'Cormorant Garamond (Classic Serif)'), ('Poppins', 'Poppins (Friendly Sans)'), ('Montserrat', 'Montserrat (Bold Sans)'), ('Roboto', 'Roboto (Clean Sans)'), ('Lora', 'Lora (Editorial Serif)'), ('Oswald', 'Oswald (Strong Display)')], default='Inter', max_length=60)),
                ('website', models.CharField(blank=True, max_length=200)),
                ('email', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='brand_kit', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
