# Generated by Django 5.2.12 on 2026-04-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0006_brandkit'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='ai_call_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='subscription',
            name='download_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
