# Generated by Django 5.2.12 on 2026-04-08 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0007_subscription_ai_call_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='color_tags',
            field=models.JSONField(blank=True, default=list, help_text='dominant colors detected from CSS'),
        ),
        migrations.AddField(
            model_name='template',
            name='download_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='template',
            name='is_animated',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='template',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='template',
            name='is_premium',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='template',
            name='keywords',
            field=models.CharField(blank=True, help_text='Comma-separated SEO keywords', max_length=400),
        ),
        migrations.AddField(
            model_name='template',
            name='language_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='template',
            name='meta_description',
            field=models.CharField(blank=True, max_length=320),
        ),
        migrations.AddField(
            model_name='template',
            name='meta_title',
            field=models.CharField(blank=True, max_length=180),
        ),
        migrations.AddField(
            model_name='template',
            name='slug',
            field=models.SlugField(blank=True, max_length=160),
        ),
        migrations.AddField(
            model_name='template',
            name='style_tags',
            field=models.JSONField(blank=True, default=list, help_text='modern, vintage, minimal, bold, elegant, etc.'),
        ),
        migrations.AddField(
            model_name='template',
            name='sub_category',
            field=models.CharField(blank=True, db_index=True, help_text='hindu, muslim, diwali, holi, etc.', max_length=40),
        ),
        migrations.AddField(
            model_name='template',
            name='tags',
            field=models.JSONField(blank=True, default=list, help_text='badges: new, hot, trending, animated, indian, premium, free, editor_pick'),
        ),
        migrations.AddField(
            model_name='template',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='template',
            name='view_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['category', 'is_featured'], name='generator_t_categor_547565_idx'),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['category', '-download_count'], name='generator_t_categor_ecdd7e_idx'),
        ),
        migrations.AddIndex(
            model_name='template',
            index=models.Index(fields=['-created_at'], name='generator_t_created_dc9037_idx'),
        ),
    ]
