# Generated by Django 5.2.12 on 2026-04-08 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0008_template_color_tags_template_download_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('starter', 'Starter'), ('pro', 'Pro'), ('lifetime', 'Lifetime'), ('business', 'Business')], default='starter', max_length=20),
        ),
    ]
