# Generated by Django 5.2.12 on 2026-04-08 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generator', '0009_alter_subscription_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, default='India', max_length=80)),
                ('city', models.CharField(blank=True, max_length=80)),
                ('profession', models.CharField(blank=True, choices=[('designer', 'Designer'), ('developer', 'Developer'), ('marketer', 'Marketer'), ('entrepreneur', 'Entrepreneur'), ('manager', 'Manager'), ('hr', 'HR / Recruiter'), ('teacher', 'Teacher'), ('student', 'Student'), ('other', 'Other')], max_length=20)),
                ('use_case', models.CharField(blank=True, choices=[('personal', 'Personal use'), ('freelance', 'Freelancer / solo'), ('business', 'Business / startup'), ('agency', 'Agency / studio'), ('student', 'Student'), ('teacher', 'Teacher / educator'), ('ngo', 'NGO / non-profit'), ('other', 'Other')], max_length=20)),
                ('company', models.CharField(blank=True, max_length=120)),
                ('website', models.CharField(blank=True, max_length=200)),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('hi', 'हिन्दी'), ('es', 'Español'), ('fr', 'Français'), ('de', 'Deutsch'), ('zh', '中文'), ('ar', 'العربية'), ('ru', 'Русский'), ('pt', 'Português'), ('ja', '日本語')], default='en', max_length=5)),
                ('referral_source', models.CharField(blank=True, help_text='How did they hear about us?', max_length=80)),
                ('newsletter_opt_in', models.BooleanField(default=True)),
                ('marketing_opt_in', models.BooleanField(default=False)),
                ('email_verified', models.BooleanField(default=False)),
                ('verification_token', models.CharField(blank=True, max_length=64)),
                ('avatar_url', models.CharField(blank=True, max_length=400)),
                ('bio', models.TextField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
