"""15 additional professional resume templates inspired by industry leaders."""

# Use the same RESUME_FIELDS schema from main seed file
# Sample data is shared via the main seed_templates rotation

RESUMES_PRO = [
    {'title': 'Photo Sidebar Modern', 'desc': 'Two-column with photo placeholder and skills bars.',
     'css': ".rp1{display:flex;font-family:'Segoe UI',sans-serif;max-width:780px;margin:0 auto;background:#fff;min-height:600px;box-shadow:0 24px 60px rgba(0,0,0,.1)}.rp1 .side{width:38%;background:#1e3a5f;color:#fff;padding:30px 24px;text-align:center}.rp1 .photo{width:140px;height:140px;border-radius:50%;background:linear-gradient(135deg,#3b82f6,#60a5fa);margin:0 auto 20px;display:flex;align-items:center;justify-content:center;font-size:60px;font-weight:bold;color:#fff;border:5px solid #3b82f6}.rp1 .side h1{font-size:22px;margin:0;letter-spacing:1px}.rp1 .side .role{color:#60a5fa;font-size:13px;margin:6px 0 24px}.rp1 .side h3{font-size:11px;letter-spacing:3px;text-transform:uppercase;color:#60a5fa;margin:18px 0 8px;border-bottom:1px solid #2c5282;padding-bottom:4px;text-align:left}.rp1 .side p{font-size:11px;line-height:1.6;color:#cbd5e0;text-align:left;margin:4px 0}.rp1 .main{flex:1;padding:30px 28px}.rp1 .main h2{color:#1e3a5f;font-size:15px;text-transform:uppercase;letter-spacing:2px;border-bottom:2px solid #1e3a5f;padding-bottom:4px;margin-top:18px}.rp1 .main pre{font-family:inherit;white-space:pre-wrap;font-size:12px;line-height:1.6;color:#444;margin:6px 0}",
     'html': '<div class="rp1"><div class="side"><div class="photo">{{ name|first }}</div><h1>{{ name }}</h1><div class="role">{{ title }}</div><h3>Contact</h3><p>📧 {{ email }}<br>📱 {{ phone }}<br>📍 {{ location }}</p><h3>Skills</h3><p>{{ skills }}</p><h3>Education</h3><p>{{ education }}</p></div><div class="main"><h2>About Me</h2><pre>{{ summary }}</pre><h2>Experience</h2><pre>{{ experience }}</pre></div></div>'},

    {'title': 'Yellow Accent Modern', 'desc': 'Modern resume with yellow accent stripe.',
     'css': ".rp2{font-family:'Segoe UI',sans-serif;max-width:780px;margin:0 auto;background:#fff;display:flex}.rp2 .side{width:30%;background:#f9d342;padding:30px 20px;color:#1a1a1a}.rp2 .side h1{font-size:26px;margin:0;font-weight:900}.rp2 .side .role{font-size:13px;margin:4px 0 22px;font-weight:600}.rp2 .side h3{font-size:11px;letter-spacing:3px;text-transform:uppercase;border-bottom:2px solid #1a1a1a;padding-bottom:4px;margin-top:18px}.rp2 .side p{font-size:11px;line-height:1.6;margin:6px 0}.rp2 .main{flex:1;padding:30px 28px;color:#333}.rp2 .main h2{color:#1a1a1a;font-size:16px;text-transform:uppercase;letter-spacing:2px;border-left:5px solid #f9d342;padding-left:10px;margin-top:18px}.rp2 .main pre{font-family:inherit;white-space:pre-wrap;font-size:12px;line-height:1.6}",
     'html': '<div class="rp2"><div class="side"><h1>{{ name }}</h1><div class="role">{{ title }}</div><h3>Contact</h3><p>{{ email }}<br>{{ phone }}<br>{{ location }}</p><h3>Skills</h3><p>{{ skills }}</p><h3>Education</h3><p>{{ education }}</p></div><div class="main"><h2>Profile</h2><pre>{{ summary }}</pre><h2>Experience</h2><pre>{{ experience }}</pre></div></div>'},

    {'title': 'Pink Banner Pro', 'desc': 'Pink top banner with bold name and photo circle.',
     'css': ".rp3{font-family:'Segoe UI',sans-serif;max-width:780px;margin:0 auto;background:#fff}.rp3 .top{background:linear-gradient(135deg,#ec4899,#f97316);color:#fff;padding:40px 40px 60px;position:relative;text-align:center}.rp3 .top h1{margin:0;font-size:38px;font-weight:900}.rp3 .top .role{margin-top:6px;font-size:15px;opacity:.95;letter-spacing:2px}.rp3 .photo{position:absolute;left:50%;bottom:-40px;transform:translateX(-50%);width:80px;height:80px;border-radius:50%;background:#fff;color:#ec4899;display:flex;align-items:center;justify-content:center;font-size:38px;font-weight:900;border:4px solid #fff;box-shadow:0 8px 20px rgba(0,0,0,.15)}.rp3 .body{padding:60px 40px 30px}.rp3 .ct{text-align:center;color:#666;font-size:13px;margin-bottom:24px}.rp3 h2{color:#ec4899;font-size:16px;text-transform:uppercase;letter-spacing:2px;border-bottom:2px solid #fce7f3;padding-bottom:4px;margin-top:18px}.rp3 pre{font-family:inherit;white-space:pre-wrap;font-size:13px;line-height:1.6;color:#444}",
     'html': '<div class="rp3"><div class="top"><h1>{{ name }}</h1><div class="role">{{ title }}</div><div class="photo">{{ name|first }}</div></div><div class="body"><div class="ct">{{ email }} · {{ phone }} · {{ location }}</div><h2>Summary</h2><pre>{{ summary }}</pre><h2>Experience</h2><pre>{{ experience }}</pre><h2>Education</h2><pre>{{ education }}</pre><h2>Skills</h2><pre>{{ skills }}</pre></div></div>'},

    {'title': 'Dark Sidebar Pro', 'desc': 'Dark sidebar with photo and contrasting white main.',
     'css': ".rp4{display:flex;font-family:'Segoe UI',sans-serif;max-width:780px;margin:0 auto;background:#fff;min-height:600px}.rp4 .side{width:35%;background:#0f172a;color:#e2e8f0;padding:30px 22px}.rp4 .photo{width:130px;height:130px;border-radius:50%;background:linear-gradient(135deg,#fbbf24,#f59e0b);margin:0 auto 18px;display:flex;align-items:center;justify-content:center;font-size:54px;font-weight:bold;color:#fff}.rp4 h1{font-size:22px;margin:0;text-align:center;color:#fff}.rp4 .role{text-align:center;color:#fbbf24;font-size:12px;letter-spacing:2px;margin:6px 0 22px;text-transform:uppercase}.rp4 h3{font-size:11px;letter-spacing:3px;text-transform:uppercase;color:#fbbf24;margin:18px 0 6px;border-bottom:1px solid #1e293b;padding-bottom:4px}.rp4 .side p{font-size:11px;line-height:1.6;color:#cbd5e0}.rp4 .main{flex:1;padding:30px 28px}.rp4 .main h2{color:#0f172a;font-size:15px;text-transform:uppercase;letter-spacing:2px;margin-top:18px;border-bottom:3px solid #fbbf24;padding-bottom:4px;display:inline-block}.rp4 pre{font-family:inherit;white-space:pre-wrap;font-size:12px;line-height:1.6;color:#444;margin:8px 0}",
     'html': '<div class="rp4"><div class="side"><div class="photo">{{ name|first }}</div><h1>{{ name }}</h1><div class="role">{{ title }}</div><h3>Contact</h3><p>📧 {{ email }}<br>📱 {{ phone }}<br>📍 {{ location }}</p><h3>Skills</h3><p>{{ skills }}</p><h3>Education</h3><p>{{ education }}</p></div><div class="main"><h2>Profile</h2><pre>{{ summary }}</pre><h2>Experience</h2><pre>{{ experience }}</pre></div></div>'},

    {'title': 'Corporate Navy Stripe', 'desc': 'Navy header stripe with structured sections.',
     'css': ".rp5{font-family:'Segoe UI',sans-serif;max-width:780px;margin:0 auto;background:#fff}.rp5 .top{background:#1e40af;color:#fff;padding:34px 40px;display:flex;justify-content:space-between;align-items:center;border-bottom:6px solid #fbbf24}.rp5 .top h1{margin:0;font-size:32px;font-weight:300;letter-spacing:1px}.rp5 .top .role{color:#bfdbfe;font-size:14px;letter-spacing:3px;text-transform:uppercase;margin-top:4px}.rp5 .top .ct{text-align:right;font-size:12px;color:#dbeafe;line-height:1.7}.rp5 .body{padding:30px 40px}.rp5 h2{color:#1e40af;font-size:14px;text-transform:uppercase;letter-spacing:3px;border-bottom:1px solid #1e40af;padding-bottom:4px;margin-top:18px}.rp5 pre{font-family:inherit;white-space:pre-wrap;font-size:13px;line-height:1.6;color:#444}",
     'html': '<div class="rp5"><div class="top"><div><h1>{{ name }}</h1><div class="role">{{ title }}</div></div><div class="ct">{{ email }}<br>{{ phone }}<br>{{ location }}</div></div><div class="body"><h2>Professional Summary</h2><pre>{{ summary }}</pre><h2>Work Experience</h2><pre>{{ experience }}</pre><h2>Education</h2><pre>{{ education }}</pre><h2>Skills</h2><pre>{{ skills }}</pre></div></div>'},

    {'title': 'Creative Purple Geo', 'desc': 'Purple geometric accents with modern feel.',
     'css': ".rp6{font-family:'Segoe UI',sans-serif;max-width:780px;margin:0 auto;background:#fff;position:relative;overflow:hidden}.rp6::before{content:'';position:absolute;top:0;right:0;width:240px;height:240px;background:linear-gradient(135deg,#8b5cf6,#ec4899);clip-path:polygon(100% 0,100% 100%,0 0)}.rp6 .top{padding:40px 40px 20px;position:relative;z-index:2}.rp6 h1{font-size:36px;margin:0;color:#0f172a;font-weight:900}.rp6 .role{color:#8b5cf6;font-size:15px;font-weight:600;margin:4px 0}.rp6 .ct{font-size:12px;color:#64748b;margin:14px 0}.rp6 .body{padding:0 40px 30px}.rp6 h2{color:#8b5cf6;font-size:16px;text-transform:uppercase;letter-spacing:2px;border-left:4px solid #ec4899;padding-left:10px;margin-top:18px}.rp6 pre{font-family:inherit;white-space:pre-wrap;font-size:13px;line-height:1.6;color:#444}",
     'html': '<div class="rp6"><div class="top"><h1>{{ name }}</h1><div class="role">{{ title }}</div><div class="ct">{{ email }} · {{ phone }} · {{ location }}</div></div><div class="body"><h2>Profile</h2><pre>{{ summary }}</pre><h2>Experience</h2><pre>{{ experience }}</pre><h2>Education</h2><pre>{{ education }}</pre><h2>Skills</h2><pre>{{ skills }}</pre></div></div>'},

    {'title': 'Clean Gray Boxed', 'desc': 'Subtle gray boxed sections, ATS-friendly.',
     'css': ".rp7{font-family:'Segoe UI',sans-serif;max-width:780px;margin:0 auto;padding:40px;background:#f8fafc;color:#334155}.rp7 .hd{background:#fff;padding:24px;border-radius:10px;border:1px solid #e2e8f0;margin-bottom:14px}.rp7 .hd h1{margin:0;font-size:30px;color:#0f172a}.rp7 .hd .role{color:#64748b;margin:4px 0}.rp7 .hd .ct{color:#64748b;font-size:13px;margin-top:10px}.rp7 .sect{background:#fff;padding:22px;border-radius:10px;border:1px solid #e2e8f0;margin-bottom:14px}.rp7 .sect h2{margin:0 0 10px;color:#0f172a;font-size:15px;text-transform:uppercase;letter-spacing:2px}.rp7 pre{font-family:inherit;white-space:pre-wrap;font-size:13px;line-height:1.6;margin:0;color:#475569}",
     'html': '<div class="rp7"><div class="hd"><h1>{{ name }}</h1><div class="role">{{ title }}</div><div class="ct">{{ email }} · {{ phone }} · {{ location }}</div></div><div class="sect"><h2>Summary</h2><pre>{{ summary }}</pre></div><div class="sect"><h2>Experience</h2><pre>{{ experience }}</pre></div><div class="sect"><h2>Education</h2><pre>{{ education }}</pre></div><div class="sect"><h2>Skills</h2><pre>{{ skills }}</pre></div></div>'},

    {'title': 'Elegant Beige Serif', 'desc': 'Cream beige serif resume with gold accents.',
     'css': ".rp8{font-family:'Playfair Display',Georgia,serif;max-width:780px;margin:0 auto;padding:50px;background:#fdf8f0;color:#3e2723}.rp8 h1{font-size:42px;margin:0;color:#7c4f1d;letter-spacing:2px;text-align:center;font-style:italic}.rp8 .role{text-align:center;color:#a8825c;font-size:14px;letter-spacing:6px;text-transform:uppercase;margin:6px 0 14px}.rp8 .ct{text-align:center;color:#8d6e63;font-size:12px;border-top:1px solid #d7ccc8;border-bottom:1px solid #d7ccc8;padding:10px 0;margin-bottom:20px}.rp8 h2{color:#7c4f1d;font-size:16px;text-transform:uppercase;letter-spacing:4px;text-align:center;margin-top:22px}.rp8 h2::before,.rp8 h2::after{content:' — ';color:#a8825c}.rp8 pre{font-family:'Segoe UI',sans-serif;white-space:pre-wrap;font-size:13px;line-height:1.7;color:#5d4037}",
     'html': '<div class="rp8"><h1>{{ name }}</h1><div class="role">{{ title }}</div><div class="ct">{{ email }} · {{ phone }} · {{ location }}</div><h2>Profile</h2><pre>{{ summary }}</pre><h2>Experience</h2><pre>{{ experience }}</pre><h2>Education</h2><pre>{{ education }}</pre><h2>Skills</h2><pre>{{ skills }}</pre></div>'},

    {'title': 'Bold Orange Header', 'desc': 'Bold orange header with strong typography.',
     'css': ".rp9{font-family:'Segoe UI',sans-serif;max-width:780px;margin:0 auto;background:#fff}.rp9 .top{background:#ea580c;color:#fff;padding:38px 40px}.rp9 .top h1{margin:0;font-size:42px;font-weight:900;letter-spacing:1px}.rp9 .top .role{margin-top:6px;font-size:14px;letter-spacing:4px;text-transform:uppercase;opacity:.95}.rp9 .top .ct{margin-top:14px;font-size:12px;opacity:.9}.rp9 .body{padding:30px 40px;color:#333}.rp9 h2{color:#ea580c;font-size:16px;text-transform:uppercase;letter-spacing:2px;border-bottom:3px solid #ea580c;padding-bottom:4px;display:inline-block;margin-top:18px}.rp9 pre{font-family:inherit;white-space:pre-wrap;font-size:13px;line-height:1.6}",
     'html': '<div class="rp9"><div class="top"><h1>{{ name }}</h1><div class="role">{{ title }}</div><div class="ct">{{ email }} · {{ phone }} · {{ location }}</div></div><div class="body"><h2>Summary</h2><pre>{{ summary }}</pre><h2>Experience</h2><pre>{{ experience }}</pre><h2>Education</h2><pre>{{ education }}</pre><h2>Skills</h2><pre>{{ skills }}</pre></div></div>'},

    {'title': 'Tech Mint Modern', 'desc': 'Mint green tech-style resume.',
     'css': ".rp10{font-family:'Segoe UI',sans-serif;max-width:780px;margin:0 auto;background:#fff;display:flex}.rp10 .side{width:32%;background:#10b981;color:#fff;padding:30px 22px}.rp10 .side h1{font-size:24px;margin:0;font-weight:900}.rp10 .side .role{font-size:12px;margin:6px 0 20px;letter-spacing:1px}.rp10 .side h3{font-size:11px;letter-spacing:3px;text-transform:uppercase;border-bottom:2px solid #fff;padding-bottom:4px;margin-top:18px}.rp10 .side p{font-size:11px;line-height:1.6;margin:6px 0}.rp10 .main{flex:1;padding:30px 28px}.rp10 .main h2{color:#10b981;font-size:15px;text-transform:uppercase;letter-spacing:2px;border-bottom:2px solid #d1fae5;padding-bottom:4px;margin-top:18px}.rp10 pre{font-family:inherit;white-space:pre-wrap;font-size:12px;line-height:1.6;color:#444}",
     'html': '<div class="rp10"><div class="side"><h1>{{ name }}</h1><div class="role">{{ title }}</div><h3>Contact</h3><p>{{ email }}<br>{{ phone }}<br>{{ location }}</p><h3>Education</h3><p>{{ education }}</p><h3>Skills</h3><p>{{ skills }}</p></div><div class="main"><h2>About</h2><pre>{{ summary }}</pre><h2>Experience</h2><pre>{{ experience }}</pre></div></div>'},

    {'title': 'Architect Black Border', 'desc': 'Bold black border architectural style.',
     'css': ".rp11{font-family:'Helvetica',Arial,sans-serif;max-width:780px;margin:0 auto;padding:40px;background:#fff;color:#000;border:8px solid #000}.rp11 h1{margin:0;font-size:40px;letter-spacing:4px;font-weight:900;border-bottom:4px solid #000;padding-bottom:14px}.rp11 .role{font-size:13px;letter-spacing:6px;text-transform:uppercase;margin:14px 0 6px;color:#666}.rp11 .ct{font-size:12px;letter-spacing:1px;color:#666;margin-bottom:24px}.rp11 h2{font-size:14px;letter-spacing:4px;text-transform:uppercase;margin-top:22px;background:#000;color:#fff;padding:6px 12px;display:inline-block}.rp11 pre{font-family:'Segoe UI',sans-serif;white-space:pre-wrap;font-size:13px;line-height:1.6;color:#333}",
     'html': '<div class="rp11"><h1>{{ name }}</h1><div class="role">{{ title }}</div><div class="ct">{{ email }} · {{ phone }} · {{ location }}</div><h2>Summary</h2><pre>{{ summary }}</pre><h2>Experience</h2><pre>{{ experience }}</pre><h2>Education</h2><pre>{{ education }}</pre><h2>Skills</h2><pre>{{ skills }}</pre></div>'},

    {'title': 'Photo Top Center', 'desc': 'Photo at top center with name below.',
     'css': ".rp12{font-family:'Segoe UI',sans-serif;max-width:780px;margin:0 auto;padding:40px;background:#fff;text-align:center}.rp12 .photo{width:120px;height:120px;border-radius:50%;background:linear-gradient(135deg,#3b82f6,#8b5cf6);margin:0 auto 16px;display:flex;align-items:center;justify-content:center;font-size:50px;color:#fff;font-weight:bold;border:6px solid #f1f5f9;box-shadow:0 10px 30px rgba(0,0,0,.1)}.rp12 h1{margin:0;font-size:32px;color:#0f172a}.rp12 .role{color:#3b82f6;font-size:15px;font-weight:600;margin:4px 0}.rp12 .ct{font-size:12px;color:#64748b;margin:14px 0 24px}.rp12 h2{color:#3b82f6;font-size:14px;text-transform:uppercase;letter-spacing:3px;border-top:1px solid #e2e8f0;border-bottom:1px solid #e2e8f0;padding:8px 0;margin-top:22px}.rp12 pre{font-family:inherit;white-space:pre-wrap;font-size:13px;line-height:1.6;color:#475569;text-align:left;margin:10px 0}",
     'html': '<div class="rp12"><div class="photo">{{ name|first }}</div><h1>{{ name }}</h1><div class="role">{{ title }}</div><div class="ct">{{ email }} · {{ phone }} · {{ location }}</div><h2>Summary</h2><pre>{{ summary }}</pre><h2>Experience</h2><pre>{{ experience }}</pre><h2>Education</h2><pre>{{ education }}</pre><h2>Skills</h2><pre>{{ skills }}</pre></div>'},

    {'title': 'Half Color Background', 'desc': 'Split background with bold left color.',
     'css': ".rp13{font-family:'Segoe UI',sans-serif;max-width:780px;margin:0 auto;background:linear-gradient(90deg,#0f172a 35%,#fff 35%);min-height:600px;display:flex}.rp13 .side{width:35%;color:#fff;padding:40px 24px}.rp13 .side h1{font-size:24px;margin:0;font-weight:900}.rp13 .side .role{color:#fbbf24;font-size:12px;letter-spacing:2px;text-transform:uppercase;margin:6px 0 22px}.rp13 .side h3{font-size:11px;letter-spacing:3px;text-transform:uppercase;color:#fbbf24;margin:18px 0 6px;border-bottom:1px solid rgba(255,255,255,.2);padding-bottom:4px}.rp13 .side p{font-size:11px;line-height:1.6;color:#cbd5e0;margin:6px 0}.rp13 .main{flex:1;padding:40px 28px;color:#0f172a}.rp13 .main h2{color:#0f172a;font-size:15px;text-transform:uppercase;letter-spacing:2px;border-bottom:2px solid #fbbf24;padding-bottom:4px;display:inline-block;margin-top:18px}.rp13 pre{font-family:inherit;white-space:pre-wrap;font-size:13px;line-height:1.6;color:#475569}",
     'html': '<div class="rp13"><div class="side"><h1>{{ name }}</h1><div class="role">{{ title }}</div><h3>Contact</h3><p>{{ email }}<br>{{ phone }}<br>{{ location }}</p><h3>Skills</h3><p>{{ skills }}</p><h3>Education</h3><p>{{ education }}</p></div><div class="main"><h2>Profile</h2><pre>{{ summary }}</pre><h2>Experience</h2><pre>{{ experience }}</pre></div></div>'},

    {'title': 'Brick Red Classic', 'desc': 'Classic brick red sidebar layout.',
     'css': ".rp14{font-family:Georgia,serif;max-width:780px;margin:0 auto;background:#fff;display:flex}.rp14 .side{width:30%;background:#9b2c2c;color:#fff;padding:30px 22px}.rp14 .side h1{font-size:22px;margin:0;font-style:italic}.rp14 .side .role{font-size:12px;margin:6px 0 22px;letter-spacing:1px;color:#fed7d7}.rp14 .side h3{font-size:11px;letter-spacing:2px;text-transform:uppercase;border-bottom:1px solid #c53030;padding-bottom:4px;margin-top:18px}.rp14 .side p{font-size:11px;line-height:1.6;color:#fed7d7;margin:6px 0}.rp14 .main{flex:1;padding:30px 28px;color:#222}.rp14 .main h2{color:#9b2c2c;font-size:16px;font-style:italic;border-bottom:2px solid #9b2c2c;padding-bottom:4px;margin-top:18px}.rp14 pre{font-family:'Segoe UI',sans-serif;white-space:pre-wrap;font-size:13px;line-height:1.7;color:#444}",
     'html': '<div class="rp14"><div class="side"><h1>{{ name }}</h1><div class="role">{{ title }}</div><h3>Contact</h3><p>{{ email }}<br>{{ phone }}<br>{{ location }}</p><h3>Skills</h3><p>{{ skills }}</p><h3>Education</h3><p>{{ education }}</p></div><div class="main"><h2>Profile</h2><pre>{{ summary }}</pre><h2>Experience</h2><pre>{{ experience }}</pre></div></div>'},

    {'title': 'Skill Bars Visual', 'desc': 'Visual sidebar with skill progress bars.',
     'css': ".rp15{font-family:'Segoe UI',sans-serif;max-width:780px;margin:0 auto;background:#fff;display:flex}.rp15 .side{width:35%;background:#f1f5f9;padding:30px 22px;color:#0f172a}.rp15 .photo{width:110px;height:110px;border-radius:50%;background:linear-gradient(135deg,#06b6d4,#0891b2);margin:0 auto 14px;display:flex;align-items:center;justify-content:center;font-size:46px;font-weight:bold;color:#fff}.rp15 .side h1{font-size:20px;margin:0;text-align:center}.rp15 .side .role{text-align:center;color:#06b6d4;font-size:12px;letter-spacing:1px;margin:4px 0 18px}.rp15 .side h3{font-size:11px;letter-spacing:3px;text-transform:uppercase;color:#06b6d4;margin:16px 0 8px}.rp15 .side p{font-size:11px;line-height:1.6;color:#475569;margin:4px 0}.rp15 .skill{font-size:11px;margin:6px 0}.rp15 .bar{height:6px;background:#cbd5e1;border-radius:3px;overflow:hidden;margin-top:3px}.rp15 .bar div{height:100%;background:linear-gradient(90deg,#06b6d4,#0891b2);width:85%;border-radius:3px}.rp15 .main{flex:1;padding:30px 28px}.rp15 .main h2{color:#06b6d4;font-size:15px;text-transform:uppercase;letter-spacing:2px;border-bottom:2px solid #06b6d4;padding-bottom:4px;display:inline-block;margin-top:18px}.rp15 pre{font-family:inherit;white-space:pre-wrap;font-size:12px;line-height:1.6;color:#475569}",
     'html': '<div class="rp15"><div class="side"><div class="photo">{{ name|first }}</div><h1>{{ name }}</h1><div class="role">{{ title }}</div><h3>Contact</h3><p>{{ email }}<br>{{ phone }}<br>{{ location }}</p><h3>Skills</h3>{% for s in skills_list %}<div class="skill">{{ s }}<div class="bar"><div></div></div></div>{% endfor %}<h3>Education</h3><p>{{ education }}</p></div><div class="main"><h2>About</h2><pre>{{ summary }}</pre><h2>Experience</h2><pre>{{ experience }}</pre></div></div>'},
]
