"""ULTRA PREMIUM templates — 10 luxury designs for the 5 most-used categories.
Marked with 💎 prefix. Uses advanced CSS — multi-layer shadows, gradient overlays,
decorative borders, premium typography (Playfair, Cormorant), embossed effects.
"""

# ============================================================
# WEDDING — 10 LUXURY DESIGNS
# ============================================================
ULTRA_WEDDINGS = [
    {'title': '💎 Velvet Royal Maroon', 'desc': 'Velvet maroon with gold leaf borders, embossed monogram & ornate scrollwork.',
     'css': ".uw1{width:560px;margin:30px auto;background:radial-gradient(ellipse at top,#7a0019 0%,#3d0009 100%);color:#fff;padding:0;font-family:'Playfair Display','Cormorant Garamond',Georgia,serif;text-align:center;border:14px solid #1a0004;box-shadow:0 50px 100px -20px rgba(122,0,25,.6),inset 0 0 0 2px #d4af37,inset 0 0 80px rgba(255,215,128,.08);position:relative;overflow:hidden}.uw1::before{content:'';position:absolute;inset:14px;border:1px solid rgba(212,175,55,.4);pointer-events:none}.uw1::after{content:'';position:absolute;inset:18px;border:1px dashed rgba(212,175,55,.25);pointer-events:none}.uw1 .top-orn{padding:36px 40px 12px;color:#d4af37;font-size:24px;letter-spacing:14px}.uw1 .small{font-size:11px;letter-spacing:10px;color:#d4af37;text-transform:uppercase;font-family:'Inter',sans-serif;margin-bottom:14px}.uw1 .body{padding:0 60px 36px}.uw1 .mono{display:inline-block;width:60px;height:60px;border:1.5px solid #d4af37;border-radius:50%;line-height:56px;font-size:24px;color:#d4af37;font-style:italic;margin:0 auto 14px}.uw1 h1{font-size:56px;margin:8px 0 0;color:#fff;font-style:italic;font-weight:400;letter-spacing:2px;text-shadow:0 2px 30px rgba(212,175,55,.4)}.uw1 .amp{font-size:38px;color:#d4af37;font-style:italic;margin:6px 0;font-family:'Cormorant Garamond',serif}.uw1 .msg{font-family:'Cormorant Garamond',serif;font-style:italic;font-size:16px;color:#f5d28a;margin:18px 20px;line-height:1.7}.uw1 .info{margin-top:18px;padding-top:18px;border-top:1px solid rgba(212,175,55,.3);font-family:'Inter',sans-serif;font-size:13px;line-height:1.9;color:#fff8e1}.uw1 .info strong{color:#d4af37;display:block;font-size:16px;letter-spacing:2px;font-family:'Playfair Display',serif}.uw1 .bottom-orn{padding:0 40px 28px;color:#d4af37;font-size:20px;letter-spacing:14px}",
     'html': '<div class="uw1"><div class="top-orn">❦ ❦ ❦</div><div class="body"><div class="small">— SAVE THE DATE —</div><div class="mono">{{ bride|first }}{{ groom|first }}</div><h1>{{ bride }}</h1><div class="amp">&amp;</div><h1>{{ groom }}</h1><div class="msg">{{ message }}</div><div class="info"><strong>{{ date }}</strong>{{ time }}<br>{{ venue|linebreaksbr }}<br><br>R · S · V · P &nbsp;&nbsp; {{ rsvp }}</div></div><div class="bottom-orn">❦ ❦ ❦</div></div>'},

    {'title': '💎 Champagne Watercolor', 'desc': 'Soft champagne watercolor with delicate floral SVG and flowing script.',
     'css': ".uw2{width:560px;margin:30px auto;background:linear-gradient(135deg,#fef9ec 0%,#f5e8d3 50%,#e8d5b7 100%);color:#5d4037;padding:60px 50px;font-family:'Cormorant Garamond',Georgia,serif;text-align:center;box-shadow:0 50px 100px -20px rgba(212,175,55,.4),inset 0 0 0 1px rgba(212,175,55,.3);position:relative;overflow:hidden}.uw2::before{content:'';position:absolute;top:-100px;right:-100px;width:300px;height:300px;background:radial-gradient(circle,rgba(244,143,177,.3),transparent 70%);border-radius:50%;filter:blur(40px)}.uw2::after{content:'';position:absolute;bottom:-100px;left:-100px;width:300px;height:300px;background:radial-gradient(circle,rgba(216,180,254,.3),transparent 70%);border-radius:50%;filter:blur(40px)}.uw2 .content{position:relative}.uw2 .florals{font-size:38px;letter-spacing:14px;color:#d48345}.uw2 .small{font-size:11px;letter-spacing:8px;color:#a8825c;text-transform:uppercase;font-family:'Inter',sans-serif;margin:14px 0}.uw2 h1{font-size:64px;margin:10px 0 4px;color:#7a4f1d;font-style:italic;font-weight:500;letter-spacing:1px;line-height:1}.uw2 .amp{font-size:46px;color:#d48345;font-style:italic;margin:6px 0;font-family:'Playfair Display',serif}.uw2 .msg{font-style:italic;font-size:15px;color:#7a5a40;margin:18px 30px;line-height:1.7}.uw2 .divider{display:flex;align-items:center;gap:12px;margin:18px 0}.uw2 .divider .line{flex:1;height:1px;background:linear-gradient(90deg,transparent,#d48345,transparent)}.uw2 .divider .dot{font-size:12px;color:#d48345}.uw2 .info{font-family:'Inter',sans-serif;font-size:13px;line-height:1.9;color:#5d4037}.uw2 .info strong{color:#7a4f1d;display:block;font-size:18px;font-family:'Playfair Display',serif;font-style:italic;font-weight:500;letter-spacing:1px;margin-bottom:4px}",
     'html': '<div class="uw2"><div class="content"><div class="florals">❀ ❀ ❀</div><div class="small">SAVE THE DATE</div><h1>{{ bride }}</h1><div class="amp">&amp;</div><h1>{{ groom }}</h1><div class="divider"><div class="line"></div><div class="dot">◆</div><div class="line"></div></div><div class="msg">{{ message }}</div><div class="info"><strong>{{ date }}</strong>{{ time }}<br>{{ venue|linebreaksbr }}<br><br>RSVP · {{ rsvp }}</div></div></div>'},

    {'title': '💎 Art Deco Onyx', 'desc': '1920s art deco with onyx black, gold geometric frame & diamond motifs.',
     'css': ".uw3{width:560px;margin:30px auto;background:#0a0a0a;color:#fff;padding:0;font-family:'Playfair Display','Cormorant Garamond',serif;text-align:center;position:relative;border:6px solid #d4af37;box-shadow:0 50px 100px -20px rgba(0,0,0,.8),inset 0 0 0 2px #0a0a0a,inset 0 0 0 4px #d4af37}.uw3::before{content:'';position:absolute;inset:12px;border:1px solid rgba(212,175,55,.3);pointer-events:none}.uw3 .deco-top{padding:30px 0 12px;background:linear-gradient(180deg,#1a1a1a,#0a0a0a)}.uw3 .deco-top svg{display:block;margin:0 auto}.uw3 .body{padding:14px 50px 40px}.uw3 .small{font-size:10px;letter-spacing:10px;color:#d4af37;text-transform:uppercase;font-family:'Inter',sans-serif;margin:8px 0 14px}.uw3 h1{font-size:54px;margin:10px 0 4px;color:#fff;font-style:italic;font-weight:400;letter-spacing:3px}.uw3 .amp{font-family:'Cormorant Garamond',serif;font-size:42px;color:#d4af37;font-style:italic;margin:8px 0}.uw3 .diamonds{display:flex;justify-content:center;gap:12px;margin:18px 0;color:#d4af37;font-size:18px}.uw3 .msg{font-family:'Cormorant Garamond',serif;font-style:italic;font-size:15px;color:#a8a8a8;margin:14px 20px;line-height:1.7}.uw3 .info{font-family:'Inter',sans-serif;font-size:12px;line-height:1.9;color:#cbcbcb;margin-top:18px;padding-top:14px;border-top:1px solid rgba(212,175,55,.4)}.uw3 .info strong{color:#d4af37;display:block;font-size:14px;letter-spacing:3px;text-transform:uppercase}",
     'html': '<div class="uw3"><div class="deco-top"><svg width="80" height="40" viewBox="0 0 80 40"><path d="M40 5 L50 15 L60 5 L70 15 L60 25 L70 35 L60 25 L50 35 L40 25 L30 35 L20 25 L10 35 L20 25 L10 15 L20 5 L30 15 Z" fill="none" stroke="#d4af37" stroke-width="1"/></svg></div><div class="body"><div class="small">— THE WEDDING OF —</div><h1>{{ bride }}</h1><div class="amp">&amp;</div><h1>{{ groom }}</h1><div class="diamonds">◆ ◇ ◆ ◇ ◆</div><div class="msg">{{ message }}</div><div class="info"><strong>{{ date }}</strong>{{ time }}<br>{{ venue|linebreaksbr }}<br>RSVP · {{ rsvp }}</div></div></div>'},

    {'title': '💎 Emerald Botanical Lux', 'desc': 'Deep emerald with gold botanical illustrations and pearl-white accents.',
     'css': ".uw4{width:560px;margin:30px auto;background:linear-gradient(135deg,#064e3b 0%,#022c22 100%);color:#fff;padding:0;font-family:'Cormorant Garamond',Georgia,serif;text-align:center;position:relative;box-shadow:0 50px 100px -20px rgba(6,78,59,.6);overflow:hidden}.uw4::before{content:'';position:absolute;top:0;left:0;right:0;height:6px;background:linear-gradient(90deg,#d4af37,#f5d28a,#d4af37)}.uw4::after{content:'';position:absolute;bottom:0;left:0;right:0;height:6px;background:linear-gradient(90deg,#d4af37,#f5d28a,#d4af37)}.uw4 .content{padding:60px 50px}.uw4 .leaves{font-size:32px;color:#d4af37;letter-spacing:8px;margin-bottom:8px}.uw4 .small{font-size:10px;letter-spacing:10px;color:#d4af37;text-transform:uppercase;font-family:'Inter',sans-serif;margin:14px 0}.uw4 h1{font-size:58px;margin:10px 0 4px;color:#fff8e1;font-style:italic;font-weight:500;letter-spacing:2px;line-height:1}.uw4 .amp{font-size:44px;color:#d4af37;font-style:italic;font-family:'Playfair Display',serif;margin:6px 0}.uw4 .msg{font-style:italic;font-size:15px;color:#a7f3d0;margin:18px 30px;line-height:1.7}.uw4 .info{font-family:'Inter',sans-serif;margin-top:18px;padding-top:14px;border-top:1px solid rgba(212,175,55,.4);font-size:13px;line-height:1.9;color:#fff8e1}.uw4 .info strong{color:#d4af37;display:block;font-family:'Playfair Display',serif;font-size:18px;font-style:italic;font-weight:500;margin-bottom:4px}",
     'html': '<div class="uw4"><div class="content"><div class="leaves">❦ 🌿 ❦</div><div class="small">CELEBRATE WITH US</div><h1>{{ bride }}</h1><div class="amp">&amp;</div><h1>{{ groom }}</h1><div class="msg">{{ message }}</div><div class="info"><strong>{{ date }}</strong>{{ time }}<br>{{ venue|linebreaksbr }}<br>RSVP · {{ rsvp }}</div></div></div>'},

    {'title': '💎 Editorial Vogue Black', 'desc': 'Magazine-cover editorial — bold serif, asymmetric, fashion-week feel.',
     'css': ".uw5{width:560px;margin:30px auto;background:#fff;padding:0;font-family:'Playfair Display',Georgia,serif;color:#0a0a0a;border:1px solid #0a0a0a;box-shadow:0 50px 100px -20px rgba(0,0,0,.3);position:relative}.uw5 .top-bar{background:#0a0a0a;color:#fff;padding:14px 30px;font-family:'Inter',sans-serif;font-size:10px;letter-spacing:6px;display:flex;justify-content:space-between;text-transform:uppercase}.uw5 .body{padding:50px 40px}.uw5 .issue{font-family:'Inter',sans-serif;font-size:11px;color:#a3a3a3;letter-spacing:4px;text-transform:uppercase;margin-bottom:14px}.uw5 h1{font-size:84px;line-height:.85;margin:10px 0;color:#0a0a0a;font-weight:900;letter-spacing:-3px;text-align:left}.uw5 h1.right{text-align:right;color:#dc2626;font-style:italic;font-weight:400}.uw5 .ampline{display:flex;align-items:center;gap:14px;margin:8px 0}.uw5 .ampline::before,.uw5 .ampline::after{content:'';flex:1;height:1px;background:#0a0a0a}.uw5 .ampline span{font-family:'Cormorant Garamond',serif;font-style:italic;font-size:32px;color:#dc2626}.uw5 .quote{font-style:italic;font-size:16px;color:#525252;margin:24px 20px;line-height:1.6;text-align:left;border-left:3px solid #dc2626;padding-left:18px}.uw5 .info{font-family:'Inter',sans-serif;font-size:12px;color:#525252;letter-spacing:1px;display:flex;justify-content:space-between;border-top:2px solid #0a0a0a;padding-top:14px;margin-top:18px}.uw5 .info strong{color:#0a0a0a;display:block;font-size:14px;letter-spacing:2px;text-transform:uppercase;font-family:'Playfair Display',serif;font-weight:700}",
     'html': '<div class="uw5"><div class="top-bar"><span>VOGUE WEDDING</span><span>VOL. 01</span></div><div class="body"><div class="issue">— Special Edition · Save the date —</div><h1>{{ bride }}</h1><div class="ampline"><span>and</span></div><h1 class="right">{{ groom }}</h1><div class="quote">"{{ message }}"</div><div class="info"><div><strong>{{ date }}</strong>{{ time }}</div><div style="text-align:right"><strong>VENUE</strong>{{ venue }}</div></div></div></div>'},

    {'title': '💎 Soft Blush Couture', 'desc': 'Couture blush pink with gold script flourishes & delicate ribbon dividers.',
     'css': ".uw6{width:560px;margin:30px auto;background:linear-gradient(180deg,#fef0ef 0%,#fce4ec 50%,#fbcfe8 100%);color:#9d174d;padding:60px 50px;font-family:'Cormorant Garamond',Georgia,serif;text-align:center;box-shadow:0 50px 100px -20px rgba(236,72,153,.3);position:relative;overflow:hidden}.uw6::before{content:'';position:absolute;top:24px;left:24px;right:24px;bottom:24px;border:1px solid rgba(157,23,77,.2);pointer-events:none}.uw6::after{content:'';position:absolute;top:30px;left:30px;right:30px;bottom:30px;border:1px dashed rgba(157,23,77,.15);pointer-events:none}.uw6 .florals{font-size:38px;letter-spacing:10px;color:#ec4899}.uw6 .small{font-family:'Inter',sans-serif;font-size:10px;letter-spacing:10px;color:#9d174d;text-transform:uppercase;margin:14px 0;font-weight:600}.uw6 h1{font-size:62px;margin:10px 0 4px;color:#9d174d;font-style:italic;font-weight:500;letter-spacing:1px;line-height:1}.uw6 .amp{font-size:46px;color:#ec4899;font-style:italic;font-family:'Playfair Display',serif;margin:6px 0}.uw6 .ribbon{display:flex;align-items:center;gap:14px;margin:18px 0}.uw6 .ribbon .line{flex:1;height:1px;background:linear-gradient(90deg,transparent,#ec4899,transparent)}.uw6 .ribbon .heart{font-size:14px;color:#ec4899}.uw6 .msg{font-style:italic;font-size:15px;color:#9d174d;margin:14px 30px;line-height:1.7;opacity:.85}.uw6 .info{font-family:'Inter',sans-serif;margin-top:18px;padding-top:14px;border-top:1px solid rgba(157,23,77,.3);font-size:13px;line-height:1.9;color:#9d174d}.uw6 .info strong{color:#831843;display:block;font-family:'Playfair Display',serif;font-style:italic;font-size:18px;font-weight:500;margin-bottom:4px}",
     'html': '<div class="uw6"><div class="florals">✿ ❀ ✿</div><div class="small">— TWO SOULS · ONE LOVE —</div><h1>{{ bride }}</h1><div class="amp">&amp;</div><h1>{{ groom }}</h1><div class="ribbon"><div class="line"></div><div class="heart">♡</div><div class="line"></div></div><div class="msg">{{ message }}</div><div class="info"><strong>{{ date }}</strong>{{ time }}<br>{{ venue|linebreaksbr }}<br>RSVP · {{ rsvp }}</div></div>'},

    {'title': '💎 Midnight Garden', 'desc': 'Deep navy with constellation patterns and silver script.',
     'css': ".uw7{width:560px;margin:30px auto;background:radial-gradient(ellipse at top,#1e1b4b 0%,#0f0f23 100%);color:#fff;padding:60px 50px;font-family:'Cormorant Garamond',Georgia,serif;text-align:center;border:1px solid #6366f1;box-shadow:0 50px 100px -20px rgba(15,15,35,.8),inset 0 0 80px rgba(99,102,241,.1);position:relative;overflow:hidden}.uw7::before{content:'';position:absolute;top:0;left:0;right:0;height:1px;background:linear-gradient(90deg,transparent,#a5b4fc,transparent)}.uw7::after{content:'';position:absolute;bottom:0;left:0;right:0;height:1px;background:linear-gradient(90deg,transparent,#a5b4fc,transparent)}.uw7 .stars{font-size:24px;letter-spacing:14px;color:#a5b4fc;margin-bottom:8px;text-shadow:0 0 12px rgba(165,180,252,.6)}.uw7 .small{font-family:'Inter',sans-serif;font-size:10px;letter-spacing:10px;color:#a5b4fc;text-transform:uppercase;margin:14px 0;font-weight:500}.uw7 h1{font-size:60px;margin:8px 0 4px;color:#f5f3ff;font-style:italic;font-weight:400;letter-spacing:2px;line-height:1;text-shadow:0 0 30px rgba(165,180,252,.3)}.uw7 .amp{font-size:42px;color:#a5b4fc;font-style:italic;font-family:'Playfair Display',serif;margin:6px 0}.uw7 .moon{font-size:24px;color:#fcd34d;margin:14px 0}.uw7 .msg{font-style:italic;font-size:15px;color:#c7d2fe;margin:14px 30px;line-height:1.7}.uw7 .info{font-family:'Inter',sans-serif;margin-top:18px;padding-top:14px;border-top:1px solid rgba(165,180,252,.4);font-size:13px;line-height:1.9;color:#e0e7ff}.uw7 .info strong{color:#a5b4fc;display:block;font-family:'Playfair Display',serif;font-style:italic;font-size:18px;font-weight:500;margin-bottom:4px}",
     'html': '<div class="uw7"><div class="stars">✦ ✧ ✦ ✧ ✦</div><div class="small">— UNDER THE STARS —</div><h1>{{ bride }}</h1><div class="amp">&amp;</div><h1>{{ groom }}</h1><div class="moon">☾ ★ ☽</div><div class="msg">{{ message }}</div><div class="info"><strong>{{ date }}</strong>{{ time }}<br>{{ venue|linebreaksbr }}<br>RSVP · {{ rsvp }}</div></div>'},

    {'title': '💎 Sicilian Terracotta', 'desc': 'Mediterranean terracotta with olive branches and warm sun-baked palette.',
     'css': ".uw8{width:560px;margin:30px auto;background:linear-gradient(135deg,#fef3e2 0%,#fde0c1 100%);color:#7c2d12;padding:60px 50px;font-family:'Cormorant Garamond',Georgia,serif;text-align:center;border:1px solid #c4501d;box-shadow:0 50px 100px -20px rgba(196,80,29,.3);position:relative}.uw8::before{content:'';position:absolute;top:18px;left:18px;right:18px;bottom:18px;border:6px double #c4501d;pointer-events:none}.uw8 .content{position:relative;padding:14px}.uw8 .olive{font-size:32px;color:#7c2d12;letter-spacing:14px}.uw8 .small{font-family:'Inter',sans-serif;font-size:10px;letter-spacing:10px;color:#c4501d;text-transform:uppercase;margin:14px 0;font-weight:600}.uw8 h1{font-size:58px;margin:10px 0 4px;color:#7c2d12;font-style:italic;font-weight:500;letter-spacing:1px;line-height:1}.uw8 .amp{font-size:44px;color:#c4501d;font-style:italic;font-family:'Playfair Display',serif;margin:6px 0}.uw8 .msg{font-style:italic;font-size:15px;color:#7c2d12;margin:14px 30px;line-height:1.7;opacity:.85}.uw8 .sun{font-size:20px;color:#f59e0b;margin:14px 0;letter-spacing:8px}.uw8 .info{font-family:'Inter',sans-serif;margin-top:18px;padding-top:14px;border-top:2px solid #c4501d;font-size:13px;line-height:1.9;color:#7c2d12}.uw8 .info strong{color:#7c2d12;display:block;font-family:'Playfair Display',serif;font-style:italic;font-size:18px;font-weight:500;margin-bottom:4px}",
     'html': '<div class="uw8"><div class="content"><div class="olive">🌿 ☀ 🌿</div><div class="small">— SUMMER WEDDING —</div><h1>{{ bride }}</h1><div class="amp">&amp;</div><h1>{{ groom }}</h1><div class="sun">◆ ◆ ◆</div><div class="msg">{{ message }}</div><div class="info"><strong>{{ date }}</strong>{{ time }}<br>{{ venue|linebreaksbr }}<br>RSVP · {{ rsvp }}</div></div></div>'},

    {'title': '💎 Pearl White Cathedral', 'desc': 'Pearl white with cathedral arch frame, gold filigree, and royal serif.',
     'css': ".uw9{width:560px;margin:30px auto;background:#fffaf0;color:#1c1917;padding:0;font-family:'Playfair Display',serif;text-align:center;border:2px solid #d4af37;box-shadow:0 50px 100px -20px rgba(212,175,55,.4);position:relative}.uw9 .arch{padding:40px 50px 14px;border-bottom:1px solid #d4af37;background:linear-gradient(180deg,#fef9ec 0%,#fffaf0 100%);position:relative;border-radius:200px 200px 0 0;margin:14px 14px 0;border:1px solid #d4af37;border-bottom:none}.uw9 .arch::before{content:'';position:absolute;inset:6px;border:1px solid #d4af37;border-radius:200px 200px 0 0;border-bottom:none;pointer-events:none}.uw9 .ico{font-size:36px;color:#d4af37;margin-top:14px}.uw9 .small{font-family:'Inter',sans-serif;font-size:10px;letter-spacing:8px;color:#a8825c;text-transform:uppercase;font-weight:600;margin:8px 0}.uw9 .body{padding:24px 50px 40px}.uw9 h1{font-size:54px;margin:10px 0 4px;color:#3c2415;font-style:italic;font-weight:400;letter-spacing:1px;line-height:1}.uw9 .amp{font-size:42px;color:#d4af37;font-style:italic;font-family:'Cormorant Garamond',serif;margin:6px 0}.uw9 .msg{font-family:'Cormorant Garamond',serif;font-style:italic;font-size:16px;color:#5d4037;margin:14px 30px;line-height:1.7}.uw9 .info{font-family:'Inter',sans-serif;margin-top:18px;padding-top:14px;border-top:1px solid #d4af37;font-size:13px;line-height:1.9;color:#5d4037}.uw9 .info strong{color:#3c2415;display:block;font-family:'Playfair Display',serif;font-style:italic;font-size:18px;font-weight:500;margin-bottom:4px}",
     'html': '<div class="uw9"><div class="arch"><div class="ico">⛪</div><div class="small">— HOLY MATRIMONY —</div></div><div class="body"><h1>{{ bride }}</h1><div class="amp">&amp;</div><h1>{{ groom }}</h1><div class="msg">{{ message }}</div><div class="info"><strong>{{ date }}</strong>{{ time }}<br>{{ venue|linebreaksbr }}<br>RSVP · {{ rsvp }}</div></div></div>'},

    {'title': '💎 Royal Mughal Heritage', 'desc': 'Royal Mughal palette — deep teal, gold, ornate borders, Sanskrit blessing.',
     'css': ".uw10{width:560px;margin:30px auto;background:radial-gradient(ellipse at top,#0e7490 0%,#083344 100%);color:#fff;padding:0;font-family:'Cormorant Garamond',Georgia,serif;text-align:center;border:8px solid #0c4a6e;box-shadow:0 50px 100px -20px rgba(8,51,68,.7),inset 0 0 0 2px #d4af37;position:relative;overflow:hidden}.uw10::before{content:'';position:absolute;inset:8px;border:1px solid rgba(212,175,55,.5);pointer-events:none}.uw10 .top{padding:30px 0 12px;background:linear-gradient(180deg,rgba(212,175,55,.15),transparent)}.uw10 .top .ico{font-size:36px;color:#d4af37}.uw10 .top .blessing{font-family:'Inter',sans-serif;font-size:13px;color:#d4af37;font-style:italic;margin-top:8px;line-height:1.6}.uw10 .body{padding:14px 50px 40px}.uw10 .small{font-family:'Inter',sans-serif;font-size:11px;letter-spacing:8px;color:#67e8f9;text-transform:uppercase;font-weight:600;margin:14px 0}.uw10 h1{font-size:56px;margin:10px 0 4px;color:#fff;font-style:italic;font-weight:400;letter-spacing:2px;line-height:1;text-shadow:0 2px 30px rgba(212,175,55,.4)}.uw10 .amp{font-size:42px;color:#d4af37;font-style:italic;font-family:'Playfair Display',serif;margin:6px 0;letter-spacing:8px}.uw10 .msg{font-style:italic;font-size:15px;color:#a5f3fc;margin:14px 30px;line-height:1.7}.uw10 .info{font-family:'Inter',sans-serif;margin-top:18px;padding-top:14px;border-top:1px solid rgba(212,175,55,.5);font-size:13px;line-height:1.9;color:#cffafe}.uw10 .info strong{color:#d4af37;display:block;font-family:'Playfair Display',serif;font-style:italic;font-size:18px;font-weight:500;margin-bottom:4px}",
     'html': '<div class="uw10"><div class="top"><div class="ico">🕌</div><div class="blessing">|| श्री गणेशाय नमः ||<br>With divine blessings</div></div><div class="body"><div class="small">— THE GRAND WEDDING —</div><h1>{{ bride }}</h1><div class="amp">~ WEDS ~</div><h1>{{ groom }}</h1><div class="msg">{{ message }}</div><div class="info"><strong>{{ date }}</strong>{{ time }}<br>{{ venue|linebreaksbr }}<br>RSVP · {{ rsvp }}</div></div></div>'},
]


# ============================================================
# RESUME — 10 LUXURY DESIGNS
# ============================================================
ULTRA_RESUMES = [
    {'title': '💎 Park Avenue Executive', 'desc': 'Wall Street executive — deep charcoal sidebar, gold accents, commanding presence.',
     'css': ".ur1{display:flex;font-family:'Inter',sans-serif;max-width:780px;margin:0 auto;background:#fff;min-height:760px;box-shadow:0 50px 100px -20px rgba(15,23,42,.4);border:1px solid #1e293b}.ur1 .side{width:38%;background:linear-gradient(180deg,#1e293b 0%,#0f172a 100%);color:#fff;padding:50px 30px;position:relative}.ur1 .side::after{content:'';position:absolute;top:0;right:0;width:4px;height:100%;background:linear-gradient(180deg,#fbbf24,#d4af37,#fbbf24)}.ur1 .mono{width:90px;height:90px;border:2px solid #fbbf24;border-radius:50%;display:flex;align-items:center;justify-content:center;font-family:'Playfair Display',serif;font-size:38px;color:#fbbf24;margin:0 auto 18px}.ur1 .side h1{font-family:'Playfair Display',serif;font-size:30px;margin:0;text-align:center;font-weight:300;letter-spacing:1px;line-height:1.1}.ur1 .side .role{text-align:center;color:#fbbf24;font-size:11px;letter-spacing:5px;text-transform:uppercase;margin:10px 0 24px;font-weight:600}.ur1 .side h3{font-size:10px;letter-spacing:4px;text-transform:uppercase;color:#fbbf24;margin-top:24px;font-weight:700;border-bottom:1px solid rgba(251,191,36,.3);padding-bottom:6px}.ur1 .side p{font-size:11px;line-height:1.8;color:#cbd5e1;margin:8px 0}.ur1 .main{flex:1;padding:50px 38px;background:#fafafa}.ur1 .main h2{font-family:'Playfair Display',serif;font-size:18px;color:#1e293b;margin-top:22px;margin-bottom:8px;font-style:italic;font-weight:500;border-bottom:2px solid #fbbf24;padding-bottom:4px;display:inline-block}.ur1 .main pre{font-family:inherit;white-space:pre-wrap;font-size:12px;line-height:1.7;color:#475569;margin:6px 0}",
     'html': '<div class="ur1"><div class="side"><div class="mono">{{ name|first }}</div><h1>{{ name }}</h1><div class="role">{{ title }}</div><h3>Contact</h3><p>{{ email }}<br>{{ phone }}<br>{{ location }}</p><h3>Skills</h3><p>{{ skills }}</p><h3>Education</h3><p>{{ education }}</p></div><div class="main"><h2>Profile</h2><pre>{{ summary }}</pre><h2>Experience</h2><pre>{{ experience }}</pre></div></div>'},

    {'title': '💎 Milano Designer Folio', 'desc': 'Italian design portfolio — generous whitespace, accent stripe, premium typography.',
     'css': ".ur2{font-family:'Inter',sans-serif;max-width:780px;margin:0 auto;background:#fff;padding:0;box-shadow:0 50px 100px -20px rgba(0,0,0,.2)}.ur2 .top{padding:60px 60px 30px;border-left:8px solid #ec4899;background:linear-gradient(135deg,#fff 0%,#fef6f3 100%)}.ur2 .top h1{font-family:'Playfair Display',serif;font-size:54px;margin:0;color:#0a0a0a;font-weight:600;letter-spacing:-1px;line-height:1}.ur2 .top .role{font-size:14px;color:#ec4899;letter-spacing:4px;text-transform:uppercase;margin:8px 0 14px;font-weight:700}.ur2 .top .ct{font-size:11px;color:#737373;letter-spacing:1px}.ur2 .body{padding:40px 60px}.ur2 h2{font-family:'Playfair Display',serif;font-size:24px;color:#0a0a0a;margin-top:28px;font-style:italic;font-weight:500}.ur2 h2::after{content:'';display:block;width:48px;height:3px;background:linear-gradient(90deg,#ec4899,#f97316);margin-top:8px;border-radius:2px}.ur2 pre{font-family:inherit;white-space:pre-wrap;font-size:13px;line-height:1.8;color:#404040;margin:14px 0}",
     'html': '<div class="ur2"><div class="top"><h1>{{ name }}</h1><div class="role">{{ title }}</div><div class="ct">{{ email }} &nbsp;·&nbsp; {{ phone }} &nbsp;·&nbsp; {{ location }}</div></div><div class="body"><h2>About Me</h2><pre>{{ summary }}</pre><h2>Experience</h2><pre>{{ experience }}</pre><h2>Education</h2><pre>{{ education }}</pre><h2>Skills</h2><pre>{{ skills }}</pre></div></div>'},

    {'title': '💎 Tokyo Tech Monolith', 'desc': 'Japanese-grid minimalism — monospace headers, ultra-sharp typography.',
     'css': ".ur3{font-family:'JetBrains Mono','Consolas',monospace;max-width:780px;margin:0 auto;background:#fafafa;padding:50px 50px;color:#0a0a0a;border:1px solid #e5e5e5;box-shadow:0 50px 100px -20px rgba(0,0,0,.15)}.ur3 .hash{color:#dc2626;letter-spacing:2px;font-size:11px;margin-bottom:8px}.ur3 h1{font-family:'Inter',sans-serif;font-size:54px;margin:0;color:#0a0a0a;font-weight:200;letter-spacing:-2px;line-height:1}.ur3 .role{font-size:13px;color:#dc2626;margin:6px 0 22px;letter-spacing:1px}.ur3 .grid{display:grid;grid-template-columns:140px 1fr;gap:14px;font-size:12px;color:#525252;margin-bottom:24px;border-top:2px solid #0a0a0a;border-bottom:2px solid #0a0a0a;padding:14px 0}.ur3 .grid b{color:#0a0a0a;font-weight:700;letter-spacing:1px;text-transform:uppercase;font-size:10px}.ur3 h2{font-family:'Inter',sans-serif;font-size:11px;letter-spacing:5px;text-transform:uppercase;color:#dc2626;margin-top:24px;margin-bottom:6px;font-weight:700}.ur3 h2::before{content:'> ';color:#999}.ur3 pre{font-family:'Inter',sans-serif;white-space:pre-wrap;font-size:13px;line-height:1.8;color:#262626;margin:6px 0}",
     'html': '<div class="ur3"><div class="hash">// CV.001 — {{ name|upper }}</div><h1>{{ name }}</h1><div class="role">{{ title }}</div><div class="grid"><b>EMAIL</b><span>{{ email }}</span><b>PHONE</b><span>{{ phone }}</span><b>LOCATION</b><span>{{ location }}</span></div><h2>Summary</h2><pre>{{ summary }}</pre><h2>Experience</h2><pre>{{ experience }}</pre><h2>Education</h2><pre>{{ education }}</pre><h2>Skills</h2><pre>{{ skills }}</pre></div>'},

    {'title': '💎 Vienna Burgundy Heritage', 'desc': 'Old-world burgundy with double-line decorative borders.',
     'css': ".ur4{font-family:'Cormorant Garamond','Playfair Display',Georgia,serif;max-width:780px;margin:0 auto;background:#fdfaf5;color:#2a1410;padding:60px 60px;border-top:10px solid #6b1d2c;border-bottom:10px solid #6b1d2c;position:relative;box-shadow:0 50px 100px -20px rgba(107,29,44,.3)}.ur4::before{content:'';position:absolute;top:10px;left:0;right:0;height:1px;background:#d4af37}.ur4::after{content:'';position:absolute;bottom:10px;left:0;right:0;height:1px;background:#d4af37}.ur4 h1{font-size:58px;margin:0;color:#6b1d2c;letter-spacing:2px;font-weight:500;text-align:center;font-style:italic}.ur4 .role{font-style:italic;text-align:center;color:#8a4a52;font-size:18px;margin:8px 0 14px;font-family:'Playfair Display',serif}.ur4 .ct{text-align:center;font-size:12px;color:#8a4a52;letter-spacing:2px;margin-bottom:24px;font-family:'Inter',sans-serif}.ur4 .div{text-align:center;color:#d4af37;font-size:18px;letter-spacing:14px;margin:14px 0}.ur4 h2{font-family:'Playfair Display',serif;font-size:18px;letter-spacing:5px;text-transform:uppercase;color:#6b1d2c;margin-top:28px;text-align:center;font-weight:600;font-style:italic}.ur4 h2::after{content:'';display:block;width:60px;height:1px;background:#d4af37;margin:6px auto 0}.ur4 pre{font-family:'Inter',sans-serif;white-space:pre-wrap;font-size:13px;line-height:1.8;color:#3a1c18;margin:12px 0;text-align:center}",
     'html': '<div class="ur4"><h1>{{ name }}</h1><div class="role">{{ title }}</div><div class="ct">{{ email }} · {{ phone }} · {{ location }}</div><div class="div">❦ ❦ ❦</div><h2>Profile</h2><pre>{{ summary }}</pre><h2>Experience</h2><pre>{{ experience }}</pre><h2>Education</h2><pre>{{ education }}</pre><h2>Skills</h2><pre>{{ skills }}</pre></div>'},

    {'title': '💎 Copenhagen Minimal', 'desc': 'Scandinavian minimalism — pure white, hairline rules, perfect spacing.',
     'css': ".ur5{font-family:'Inter',sans-serif;max-width:780px;margin:0 auto;background:#fff;padding:80px 70px;color:#0a0a0a;box-shadow:0 50px 100px -20px rgba(0,0,0,.1)}.ur5 h1{font-size:48px;margin:0;font-weight:200;letter-spacing:1px;line-height:1}.ur5 .role{font-size:11px;letter-spacing:8px;text-transform:uppercase;color:#737373;margin:14px 0 32px;font-weight:600}.ur5 .ct{font-size:10px;letter-spacing:3px;color:#737373;display:flex;gap:30px;border-top:1px solid #0a0a0a;border-bottom:1px solid #0a0a0a;padding:18px 0;margin-bottom:32px;text-transform:uppercase;font-weight:600}.ur5 h2{font-size:11px;letter-spacing:6px;text-transform:uppercase;color:#0a0a0a;margin-top:34px;font-weight:700}.ur5 h2::before{content:'';display:inline-block;width:32px;height:1px;background:#0a0a0a;vertical-align:middle;margin-right:12px}.ur5 pre{font-family:inherit;white-space:pre-wrap;font-size:13px;line-height:1.9;color:#404040;margin:14px 0 0 44px;font-weight:300}",
     'html': '<div class="ur5"><h1>{{ name }}</h1><div class="role">{{ title }}</div><div class="ct"><span>{{ email }}</span><span>{{ phone }}</span><span>{{ location }}</span></div><h2>Profile</h2><pre>{{ summary }}</pre><h2>Experience</h2><pre>{{ experience }}</pre><h2>Education</h2><pre>{{ education }}</pre><h2>Skills</h2><pre>{{ skills }}</pre></div>'},

    {'title': '💎 Soho Magazine Spread', 'desc': 'Magazine-spread layout with bold serif and pull-quote profile.',
     'css': ".ur6{font-family:'Inter',sans-serif;max-width:780px;margin:0 auto;background:#fff;padding:0;box-shadow:0 50px 100px -20px rgba(0,0,0,.2)}.ur6 .top{padding:60px 60px 30px;background:linear-gradient(180deg,#fafafa 0%,#fff 100%);border-bottom:3px solid #0a0a0a}.ur6 .top h1{font-family:'Playfair Display',serif;font-size:78px;margin:0;color:#0a0a0a;font-weight:900;letter-spacing:-3px;line-height:.9}.ur6 .top .role{font-family:'Cormorant Garamond',serif;font-size:24px;font-style:italic;color:#dc2626;margin:8px 0 14px}.ur6 .top .ct{font-size:11px;color:#737373;letter-spacing:1px}.ur6 .body{padding:40px 60px}.ur6 .quote{font-family:'Cormorant Garamond',serif;font-size:22px;font-style:italic;color:#0a0a0a;line-height:1.5;margin:0 0 30px;padding-left:24px;border-left:3px solid #dc2626}.ur6 h2{font-family:'Playfair Display',serif;font-size:13px;letter-spacing:5px;text-transform:uppercase;color:#0a0a0a;margin-top:28px;font-weight:700;border-bottom:1px solid #0a0a0a;padding-bottom:6px;display:inline-block}.ur6 pre{font-family:inherit;white-space:pre-wrap;font-size:13px;line-height:1.8;color:#404040;margin:10px 0}",
     'html': '<div class="ur6"><div class="top"><h1>{{ name }}</h1><div class="role">— {{ title }}</div><div class="ct">{{ email }} &nbsp;·&nbsp; {{ phone }} &nbsp;·&nbsp; {{ location }}</div></div><div class="body"><div class="quote">"{{ summary }}"</div><h2>Experience</h2><pre>{{ experience }}</pre><h2>Education</h2><pre>{{ education }}</pre><h2>Skills</h2><pre>{{ skills }}</pre></div></div>'},

    {'title': '💎 Versailles Gold Crest', 'desc': 'Royal gold crest with double-border heritage frame and centered hierarchy.',
     'css': ".ur7{font-family:'Cormorant Garamond',Georgia,serif;max-width:780px;margin:0 auto;background:#fffaf0;color:#3c2415;padding:60px 60px;border:1px solid #d4af37;outline:6px double #d4af37;outline-offset:-14px;box-shadow:0 50px 100px -20px rgba(212,175,55,.3);position:relative}.ur7 .crest{text-align:center;font-size:36px;color:#d4af37;letter-spacing:14px;margin-bottom:8px}.ur7 h1{font-family:'Playfair Display',serif;font-size:54px;margin:0;color:#3c2415;letter-spacing:2px;text-align:center;font-weight:500;font-style:italic}.ur7 .role{font-style:italic;text-align:center;color:#a8825c;font-size:18px;margin:8px 0 14px;letter-spacing:3px;font-family:'Inter',sans-serif;text-transform:uppercase;font-weight:500}.ur7 .ct{text-align:center;font-size:12px;color:#a8825c;letter-spacing:2px;margin-bottom:24px;font-family:'Inter',sans-serif}.ur7 h2{font-family:'Playfair Display',serif;font-size:15px;letter-spacing:5px;text-transform:uppercase;color:#d4af37;margin-top:28px;text-align:center;font-weight:600}.ur7 h2::before{content:'§ '}.ur7 h2::after{content:' §'}.ur7 pre{font-family:'Inter',sans-serif;white-space:pre-wrap;font-size:13px;line-height:1.8;color:#5d4037;margin:12px 0;text-align:center}",
     'html': '<div class="ur7"><div class="crest">⚜ ⚜ ⚜</div><h1>{{ name }}</h1><div class="role">{{ title }}</div><div class="ct">{{ email }} · {{ phone }} · {{ location }}</div><h2>Profile</h2><pre>{{ summary }}</pre><h2>Experience</h2><pre>{{ experience }}</pre><h2>Education</h2><pre>{{ education }}</pre><h2>Skills</h2><pre>{{ skills }}</pre></div>'},

    {'title': '💎 Brooklyn Slate Modern', 'desc': 'Modern Brooklyn with split-pane and indigo gradient highlights.',
     'css': ".ur8{display:flex;font-family:'Inter',sans-serif;max-width:780px;margin:0 auto;background:#fff;min-height:760px;box-shadow:0 50px 100px -20px rgba(0,0,0,.2)}.ur8 .left{width:42%;background:#0f172a;color:#fff;padding:50px 32px;position:relative}.ur8 .left::after{content:'';position:absolute;top:0;right:0;width:6px;height:100%;background:linear-gradient(180deg,#6366f1,#a855f7,#ec4899)}.ur8 .left h1{font-family:'Playfair Display',serif;font-size:34px;margin:0;font-weight:600;letter-spacing:-.5px;line-height:1.05;color:#fff}.ur8 .left .role{font-size:11px;color:#a5b4fc;letter-spacing:4px;text-transform:uppercase;margin:8px 0 24px;font-weight:600}.ur8 .left h3{font-size:10px;letter-spacing:3px;text-transform:uppercase;color:#a5b4fc;margin-top:22px;font-weight:700}.ur8 .left p{font-size:11px;color:#cbd5e1;line-height:1.8;margin:8px 0}.ur8 .right{flex:1;padding:50px 38px}.ur8 .right h2{font-size:13px;letter-spacing:5px;text-transform:uppercase;color:#0f172a;margin-top:24px;font-weight:700}.ur8 .right h2::after{content:'';display:block;width:32px;height:3px;background:linear-gradient(90deg,#6366f1,#a855f7);margin-top:6px;border-radius:2px}.ur8 .right pre{font-family:inherit;white-space:pre-wrap;font-size:13px;line-height:1.8;color:#475569;margin:12px 0}",
     'html': '<div class="ur8"><div class="left"><h1>{{ name }}</h1><div class="role">{{ title }}</div><h3>Contact</h3><p>{{ email }}<br>{{ phone }}<br>{{ location }}</p><h3>Skills</h3><p>{{ skills }}</p><h3>Education</h3><p>{{ education }}</p></div><div class="right"><h2>Profile</h2><pre>{{ summary }}</pre><h2>Experience</h2><pre>{{ experience }}</pre></div></div>'},

    {'title': '💎 Marrakech Sunset', 'desc': 'Warm sunset gradient header with deep terracotta accents.',
     'css': ".ur9{font-family:'Inter',sans-serif;max-width:780px;margin:0 auto;background:#fff;padding:0;box-shadow:0 50px 100px -20px rgba(196,80,29,.3)}.ur9 .top{background:linear-gradient(135deg,#7c2d12 0%,#c4501d 50%,#f59e0b 100%);color:#fff;padding:50px 50px 60px;position:relative}.ur9 .top::after{content:'';position:absolute;left:0;right:0;bottom:0;height:6px;background:linear-gradient(90deg,#fef3e2,#fff,#fef3e2)}.ur9 .top h1{font-family:'Playfair Display',serif;font-size:48px;margin:0;font-weight:500;letter-spacing:1px;text-shadow:0 2px 20px rgba(0,0,0,.2)}.ur9 .top .role{font-size:13px;color:#fef3e2;letter-spacing:5px;text-transform:uppercase;margin:8px 0 18px;font-weight:600}.ur9 .top .ct{font-size:12px;color:#fef9ec;letter-spacing:1px}.ur9 .body{padding:40px 50px;background:#fef9ec}.ur9 h2{font-family:'Playfair Display',serif;font-size:22px;color:#7c2d12;margin-top:22px;font-style:italic;font-weight:500}.ur9 h2::after{content:'';display:block;width:48px;height:3px;background:linear-gradient(90deg,#c4501d,#f59e0b);margin-top:6px;border-radius:2px}.ur9 pre{font-family:inherit;white-space:pre-wrap;font-size:13px;line-height:1.8;color:#5d4037;margin:12px 0}",
     'html': '<div class="ur9"><div class="top"><h1>{{ name }}</h1><div class="role">{{ title }}</div><div class="ct">{{ email }} &nbsp;·&nbsp; {{ phone }} &nbsp;·&nbsp; {{ location }}</div></div><div class="body"><h2>About</h2><pre>{{ summary }}</pre><h2>Experience</h2><pre>{{ experience }}</pre><h2>Education</h2><pre>{{ education }}</pre><h2>Skills</h2><pre>{{ skills }}</pre></div></div>'},

    {'title': '💎 Geneva White Glove', 'desc': 'Ultra-luxe white-glove minimal — extreme padding, hairline elegance.',
     'css': ".ur10{font-family:'Inter',sans-serif;max-width:780px;margin:0 auto;background:#fff;padding:90px 80px;color:#0a0a0a;border:1px solid #0a0a0a;box-shadow:0 50px 100px -20px rgba(0,0,0,.15)}.ur10 .label{font-size:9px;letter-spacing:10px;text-transform:uppercase;color:#737373;margin-bottom:8px;font-weight:700}.ur10 h1{font-size:46px;margin:0;font-weight:200;letter-spacing:3px;line-height:1}.ur10 .role{font-size:11px;letter-spacing:8px;text-transform:uppercase;color:#525252;margin:18px 0 36px;font-weight:600}.ur10 .ct{font-size:11px;letter-spacing:3px;color:#737373;display:flex;gap:36px;border-top:1px solid #0a0a0a;border-bottom:1px solid #0a0a0a;padding:18px 0;margin-bottom:36px;text-transform:uppercase;font-weight:600}.ur10 h2{font-size:10px;letter-spacing:6px;text-transform:uppercase;color:#0a0a0a;margin-top:36px;font-weight:700}.ur10 h2::before{content:'— ';color:#737373}.ur10 pre{font-family:inherit;white-space:pre-wrap;font-size:13px;line-height:2;color:#404040;margin:14px 0 0 24px;font-weight:300;letter-spacing:.2px}",
     'html': '<div class="ur10"><div class="label">RESUME</div><h1>{{ name }}</h1><div class="role">{{ title }}</div><div class="ct"><span>{{ email }}</span><span>{{ phone }}</span><span>{{ location }}</span></div><h2>Profile</h2><pre>{{ summary }}</pre><h2>Experience</h2><pre>{{ experience }}</pre><h2>Education</h2><pre>{{ education }}</pre><h2>Skills</h2><pre>{{ skills }}</pre></div>'},
]


# ============================================================
# INVOICE — 10 LUXURY (uses dynamic items field)
# ============================================================
ULTRA_INVOICES = [
    {'title': '💎 Maison Onyx Gold', 'desc': 'Black onyx with gold leaf borders and embossed total.',
     'css': ".ui1{font-family:'Inter',sans-serif;max-width:780px;margin:0 auto;background:#0a0a0a;color:#fff;padding:60px 60px;border:1px solid #d4af37;box-shadow:0 50px 100px -20px rgba(0,0,0,.6),inset 0 0 0 6px #0a0a0a,inset 0 0 0 8px rgba(212,175,55,.3)}.ui1 .top{display:flex;justify-content:space-between;align-items:flex-start;border-bottom:1px solid #d4af37;padding-bottom:30px}.ui1 h1{font-family:'Playfair Display',serif;font-size:54px;margin:0;color:#d4af37;letter-spacing:6px;font-weight:300}.ui1 .label{font-size:9px;letter-spacing:6px;color:#737373;text-transform:uppercase;margin-bottom:8px;font-weight:700}.ui1 .meta{display:flex;justify-content:space-between;margin:30px 0;font-size:12px}.ui1 table{width:100%;border-collapse:collapse;margin-top:20px}.ui1 th{padding:14px 8px;text-align:left;border-bottom:1px solid #d4af37;color:#d4af37;font-size:9px;letter-spacing:4px;text-transform:uppercase;font-weight:700}.ui1 td{padding:18px 8px;border-bottom:1px solid #2a2a2a;font-size:13px}.ui1 .total{text-align:right;font-size:42px;font-family:'Playfair Display',serif;color:#d4af37;margin-top:24px;font-weight:300;letter-spacing:1px}.ui1 .notes{margin-top:20px;font-size:11px;color:#737373;border-top:1px solid #2a2a2a;padding-top:18px;line-height:1.7}",
     'html': '<div class="ui1"><div class="top"><div><div class="label">INVOICE</div><h1>{{ company }}</h1><div style="font-size:11px;color:#737373;margin-top:8px">{{ company_address }}</div></div><div style="text-align:right;font-size:11px"><div class="label">№</div>{{ invoice_no }}<br><br><div class="label">DATE</div>{{ date }}</div></div><div class="meta"><div><div class="label">BILL TO</div>{{ client }}<br><span style="color:#737373">{{ client_address }}</span></div></div><table><tr><th>Description</th><th>Qty</th><th>Unit Price</th><th style="text-align:right">Amount</th></tr>{% for it in items %}<tr><td>{{ it.desc }}</td><td>{{ it.qty }}</td><td>₹{{ it.price }}</td><td style="text-align:right">₹{{ it.total }}</td></tr>{% endfor %}</table><div class="total">₹{{ total }}</div><div class="notes">{{ notes }}</div></div>'},

    {'title': '💎 Editorial Cream Ledger', 'desc': 'Magazine cream invoice with editorial typography.',
     'css': ".ui2{font-family:'Cormorant Garamond',Georgia,serif;max-width:780px;margin:0 auto;background:#fef9ec;color:#1a1a1a;padding:70px 60px;box-shadow:0 50px 100px -20px rgba(212,175,55,.3);border:1px solid #d4af37}.ui2 .top{text-align:center;margin-bottom:36px}.ui2 .label{font-family:'Inter',sans-serif;font-size:11px;letter-spacing:10px;color:#a8825c;text-transform:uppercase;font-weight:700}.ui2 h1{font-size:64px;margin:14px 0 0;font-weight:500;letter-spacing:1px}.ui2 .meta{display:flex;justify-content:space-between;font-size:13px;border-top:1px solid #d4af37;border-bottom:1px solid #d4af37;padding:20px 0;margin-bottom:30px}.ui2 table{width:100%;border-collapse:collapse;font-family:'Inter',sans-serif;font-size:13px}.ui2 th{padding:14px 8px;text-align:left;border-bottom:2px solid #1a1a1a;font-size:10px;letter-spacing:3px;text-transform:uppercase;font-weight:700}.ui2 td{padding:18px 8px;border-bottom:1px solid #e5d9c5}.ui2 .total{font-family:'Cormorant Garamond',serif;font-size:48px;text-align:right;margin-top:20px;color:#a8825c;font-weight:500;font-style:italic}.ui2 .notes{font-family:'Inter',sans-serif;margin-top:20px;font-size:12px;color:#737373;border-top:1px solid #e5d9c5;padding-top:14px}",
     'html': '<div class="ui2"><div class="top"><div class="label">— INVOICE —</div><h1>{{ company }}</h1></div><div class="meta"><div><strong>{{ invoice_no }}</strong><br>{{ date }}</div><div style="text-align:right"><em>Bill To</em><br>{{ client }}<br>{{ client_address }}</div></div><table><tr><th>Description</th><th>Qty</th><th>Price</th><th style="text-align:right">Total</th></tr>{% for it in items %}<tr><td>{{ it.desc }}</td><td>{{ it.qty }}</td><td>₹{{ it.price }}</td><td style="text-align:right">₹{{ it.total }}</td></tr>{% endfor %}</table><div class="total">Total: ₹{{ total }}</div><div class="notes">{{ notes }}</div></div>'},

    {'title': '💎 Monaco Navy Premium', 'desc': 'Navy gradient header, gold accent, premium executive feel.',
     'css': ".ui3{font-family:'Inter',sans-serif;max-width:780px;margin:0 auto;background:#fff;box-shadow:0 50px 100px -20px rgba(15,23,42,.3);border:1px solid #d4af37}.ui3 .top{background:linear-gradient(135deg,#0f1c3f 0%,#1a2a52 100%);color:#fff;padding:46px 50px;border-bottom:6px solid #d4af37;position:relative}.ui3 .top::after{content:'';position:absolute;left:0;right:0;bottom:-6px;height:1px;background:#fff}.ui3 h1{font-family:'Playfair Display',serif;font-size:46px;margin:0;color:#d4af37;letter-spacing:3px;font-weight:300}.ui3 .body{padding:36px 50px}.ui3 .meta{display:flex;justify-content:space-between;font-size:13px;margin-bottom:24px}.ui3 table{width:100%;border-collapse:collapse;font-size:13px}.ui3 th{background:#0f1c3f;color:#d4af37;padding:14px;text-align:left;font-size:10px;letter-spacing:3px;text-transform:uppercase;font-weight:700}.ui3 td{padding:18px 14px;border-bottom:1px solid #f1f5f9}.ui3 .total{background:#0f1c3f;color:#d4af37;padding:24px 28px;text-align:right;font-size:32px;font-family:'Playfair Display',serif;margin-top:18px;font-weight:300}",
     'html': '<div class="ui3"><div class="top"><h1>INVOICE</h1><div style="font-size:12px;color:#d4af37;margin-top:6px;letter-spacing:1px">{{ company }} · {{ company_address }}</div></div><div class="body"><div class="meta"><div><strong>Bill To:</strong><br>{{ client }}<br>{{ client_address }}</div><div style="text-align:right"><strong>{{ invoice_no }}</strong><br>{{ date }}</div></div><table><tr><th>Description</th><th>Qty</th><th>Price</th><th>Total</th></tr>{% for it in items %}<tr><td>{{ it.desc }}</td><td>{{ it.qty }}</td><td>₹{{ it.price }}</td><td>₹{{ it.total }}</td></tr>{% endfor %}</table><div class="total">TOTAL ₹{{ total }}</div><div style="margin-top:18px;font-size:12px;color:#737373">{{ notes }}</div></div></div>'},

    {'title': '💎 Vienna Burgundy Plate', 'desc': 'Burgundy double-line ledger plate, traditional letterpress.',
     'css': ".ui4{font-family:'Cormorant Garamond',Georgia,serif;max-width:780px;margin:0 auto;background:#fdfaf5;color:#2a1410;padding:60px 60px;border-top:10px solid #6b1d2c;border-bottom:10px solid #6b1d2c;box-shadow:0 50px 100px -20px rgba(107,29,44,.3);position:relative}.ui4::before{content:'';position:absolute;top:10px;left:0;right:0;height:1px;background:#d4af37}.ui4::after{content:'';position:absolute;bottom:10px;left:0;right:0;height:1px;background:#d4af37}.ui4 h1{font-size:56px;color:#6b1d2c;margin:0;text-align:center;font-weight:500;letter-spacing:3px;font-style:italic}.ui4 .label{text-align:center;font-family:'Inter',sans-serif;font-size:11px;letter-spacing:8px;color:#8a4a52;text-transform:uppercase;margin-bottom:8px;font-weight:600}.ui4 .meta{display:flex;justify-content:space-between;margin:30px 0;font-size:13px}.ui4 table{width:100%;border-collapse:collapse;font-family:'Inter',sans-serif;font-size:13px;margin-top:20px}.ui4 th{padding:14px;text-align:left;border-top:2px solid #6b1d2c;border-bottom:2px solid #6b1d2c;color:#6b1d2c;font-size:10px;letter-spacing:3px;text-transform:uppercase;font-weight:700}.ui4 td{padding:18px 14px;border-bottom:1px solid #f3e0d4}.ui4 .total{font-family:'Cormorant Garamond',serif;font-size:42px;color:#6b1d2c;text-align:right;margin-top:18px;font-style:italic;font-weight:500}",
     'html': '<div class="ui4"><div class="label">— Invoice —</div><h1>{{ company }}</h1><div class="meta"><div>{{ company_address }}</div><div style="text-align:right">№ {{ invoice_no }}<br>{{ date }}</div></div><div style="font-family:Inter,sans-serif;font-size:13px"><strong>Bill To:</strong> {{ client }}, {{ client_address }}</div><table><tr><th>Item</th><th>Qty</th><th>Rate</th><th>Total</th></tr>{% for it in items %}<tr><td>{{ it.desc }}</td><td>{{ it.qty }}</td><td>₹{{ it.price }}</td><td>₹{{ it.total }}</td></tr>{% endfor %}</table><div class="total">Total: ₹{{ total }}</div><div style="margin-top:18px;font-size:12px;font-family:Inter,sans-serif">{{ notes }}</div></div>'},

    {'title': '💎 Tokyo Mono Pristine', 'desc': 'Sharp monospace minimalism with red accent and grid alignment.',
     'css': ".ui5{font-family:'Inter',sans-serif;max-width:780px;margin:0 auto;background:#fafafa;color:#0a0a0a;padding:60px 60px;border:1px solid #e5e5e5;box-shadow:0 50px 100px -20px rgba(0,0,0,.15)}.ui5 .hash{font-family:'Consolas',monospace;font-size:11px;color:#a3a3a3;letter-spacing:2px;text-transform:uppercase}.ui5 h1{font-size:54px;margin:8px 0;font-weight:200;letter-spacing:-1px}.ui5 .grid{display:grid;grid-template-columns:140px 1fr;gap:14px;font-size:12px;border-top:1px solid #e5e5e5;border-bottom:1px solid #e5e5e5;padding:18px 0;margin:24px 0}.ui5 .grid b{color:#0a0a0a;font-weight:700;letter-spacing:1px;text-transform:uppercase;font-size:10px}.ui5 table{width:100%;border-collapse:collapse;font-size:13px;margin-top:14px}.ui5 th{padding:12px 8px;text-align:left;font-size:10px;letter-spacing:3px;text-transform:uppercase;color:#dc2626;border-bottom:2px solid #dc2626;font-weight:700}.ui5 td{padding:18px 8px;border-bottom:1px solid #e5e5e5}.ui5 .total{text-align:right;font-size:36px;margin-top:18px;color:#dc2626;font-weight:300;letter-spacing:-1px}",
     'html': '<div class="ui5"><div class="hash">// INVOICE.{{ invoice_no }}</div><h1>{{ company }}</h1><div class="grid"><b>BILL TO</b><span>{{ client }}<br>{{ client_address }}</span><b>DATE</b><span>{{ date }}</span></div><table><tr><th>Item</th><th>Qty</th><th>Rate</th><th style="text-align:right">Total</th></tr>{% for it in items %}<tr><td>{{ it.desc }}</td><td>{{ it.qty }}</td><td>₹{{ it.price }}</td><td style="text-align:right">₹{{ it.total }}</td></tr>{% endfor %}</table><div class="total">₹{{ total }}</div><div style="margin-top:18px;font-size:12px;color:#525252">{{ notes }}</div></div>'},

    {'title': '💎 Milano Emerald Atelier', 'desc': 'Emerald & gold luxury atelier with fashion-house feel.',
     'css': ".ui6{font-family:'Inter',sans-serif;max-width:780px;margin:0 auto;background:#fff;box-shadow:0 50px 100px -20px rgba(6,78,59,.3);border:1px solid #d4af37}.ui6 .top{background:linear-gradient(135deg,#064e3b 0%,#0d3a2d 100%);color:#fff;padding:50px 50px;position:relative}.ui6 .top::after{content:'';position:absolute;left:0;right:0;bottom:0;height:6px;background:linear-gradient(90deg,#d4af37,#f5d28a,#d4af37)}.ui6 h1{font-family:'Playfair Display',serif;font-size:48px;margin:0;color:#d4af37;font-weight:400;letter-spacing:3px;font-style:italic}.ui6 .body{padding:40px 50px}.ui6 table{width:100%;border-collapse:collapse;margin-top:20px;font-size:13px}.ui6 th{padding:14px;text-align:left;border-bottom:2px solid #064e3b;color:#064e3b;font-size:10px;letter-spacing:3px;text-transform:uppercase;font-weight:700}.ui6 td{padding:18px 14px;border-bottom:1px solid #d1fae5}.ui6 .total{text-align:right;font-family:'Playfair Display',serif;font-size:42px;color:#064e3b;margin-top:20px;font-style:italic;font-weight:500}",
     'html': '<div class="ui6"><div class="top"><h1>INVOICE</h1><div style="font-size:13px;color:#d4af37;margin-top:6px;letter-spacing:1px">{{ company }}</div></div><div class="body"><div style="display:flex;justify-content:space-between;font-size:13px;margin-bottom:18px"><div><strong>Bill To:</strong> {{ client }}<br>{{ client_address }}</div><div style="text-align:right"><strong>{{ invoice_no }}</strong><br>{{ date }}</div></div><table><tr><th>Description</th><th>Qty</th><th>Rate</th><th>Total</th></tr>{% for it in items %}<tr><td>{{ it.desc }}</td><td>{{ it.qty }}</td><td>₹{{ it.price }}</td><td>₹{{ it.total }}</td></tr>{% endfor %}</table><div class="total">₹{{ total }}</div><div style="margin-top:18px;font-size:12px;color:#737373">{{ notes }}</div></div></div>'},

    {'title': '💎 Park Avenue Slate Pro', 'desc': 'Slate split-pane with amber accents.',
     'css': ".ui7{display:flex;font-family:'Inter',sans-serif;max-width:780px;margin:0 auto;background:#fff;box-shadow:0 50px 100px -20px rgba(15,23,42,.25)}.ui7 .left{width:42%;background:#0f172a;color:#fff;padding:50px 32px}.ui7 .left h1{font-family:'Playfair Display',serif;font-size:38px;margin:0;color:#fbbf24;font-weight:300}.ui7 .left .sub{font-size:11px;letter-spacing:4px;color:#94a3b8;margin-top:8px;text-transform:uppercase;font-weight:600}.ui7 .left h3{font-size:10px;letter-spacing:3px;color:#fbbf24;text-transform:uppercase;margin-top:28px;font-weight:700}.ui7 .left p{font-size:12px;color:#cbd5e1;line-height:1.7;margin:6px 0}.ui7 .right{flex:1;padding:50px 38px}.ui7 .right table{width:100%;border-collapse:collapse;font-size:13px;margin-top:14px}.ui7 .right th{padding:12px 8px;text-align:left;border-bottom:2px solid #0f172a;font-size:10px;letter-spacing:3px;text-transform:uppercase;font-weight:700}.ui7 .right td{padding:18px 8px;border-bottom:1px solid #e2e8f0}.ui7 .total{text-align:right;font-family:'Playfair Display',serif;font-size:42px;color:#0f172a;margin-top:18px;font-weight:300}",
     'html': '<div class="ui7"><div class="left"><h1>INVOICE</h1><div class="sub">{{ invoice_no }}</div><h3>From</h3><p>{{ company }}<br>{{ company_address }}</p><h3>Bill To</h3><p>{{ client }}<br>{{ client_address }}</p><h3>Date</h3><p>{{ date }}</p></div><div class="right"><table><tr><th>Item</th><th>Qty</th><th>Price</th><th>Total</th></tr>{% for it in items %}<tr><td>{{ it.desc }}</td><td>{{ it.qty }}</td><td>₹{{ it.price }}</td><td>₹{{ it.total }}</td></tr>{% endfor %}</table><div class="total">₹{{ total }}</div><div style="margin-top:18px;font-size:12px;color:#475569">{{ notes }}</div></div></div>'},

    {'title': '💎 Soho Couture Pink', 'desc': 'Couture pink editorial with italic flair and gradient header.',
     'css': ".ui8{font-family:'Inter',sans-serif;max-width:780px;margin:0 auto;background:#fef6f3;color:#1a1a1a;padding:60px 60px;position:relative;box-shadow:0 50px 100px -20px rgba(236,72,153,.25)}.ui8::before{content:'';position:absolute;top:0;left:0;right:0;height:8px;background:linear-gradient(90deg,#ec4899,#f97316,#ec4899)}.ui8 h1{font-family:'Playfair Display',serif;font-size:64px;margin:0;font-style:italic;color:#0a0a0a;font-weight:600;letter-spacing:-1px}.ui8 .label{font-size:11px;letter-spacing:5px;color:#ec4899;text-transform:uppercase;font-weight:700;margin-bottom:6px}.ui8 table{width:100%;border-collapse:collapse;font-size:13px;margin-top:20px}.ui8 th{padding:14px;text-align:left;background:#fbcfe8;color:#9d174d;font-size:10px;letter-spacing:3px;text-transform:uppercase;font-weight:700}.ui8 td{padding:18px 14px;border-bottom:1px solid #fbcfe8}.ui8 .total{text-align:right;font-family:'Playfair Display',serif;font-style:italic;font-size:48px;color:#ec4899;margin-top:20px;font-weight:500}",
     'html': '<div class="ui8"><div class="label">— INVOICE —</div><h1>{{ company }}</h1><div style="display:flex;justify-content:space-between;font-size:13px;margin-top:18px"><div>{{ company_address }}</div><div style="text-align:right">№ {{ invoice_no }}<br>{{ date }}</div></div><div style="margin-top:14px;font-size:13px"><strong>Bill To:</strong> {{ client }}</div><table><tr><th>Item</th><th>Qty</th><th>Price</th><th>Total</th></tr>{% for it in items %}<tr><td>{{ it.desc }}</td><td>{{ it.qty }}</td><td>₹{{ it.price }}</td><td>₹{{ it.total }}</td></tr>{% endfor %}</table><div class="total">₹{{ total }}</div><div style="margin-top:18px;font-size:12px;color:#737373">{{ notes }}</div></div>'},

    {'title': '💎 Geneva Pristine White', 'desc': 'Ultra-luxe white-glove with airy spacing.',
     'css': ".ui9{font-family:'Inter',sans-serif;max-width:780px;margin:0 auto;background:#fff;color:#0a0a0a;padding:90px 80px;box-shadow:0 50px 100px -20px rgba(0,0,0,.12)}.ui9 h1{font-size:42px;margin:0;font-weight:200;letter-spacing:6px}.ui9 .ct{font-size:11px;letter-spacing:3px;color:#737373;border-top:1px solid #0a0a0a;border-bottom:1px solid #0a0a0a;padding:18px 0;margin:24px 0 30px;display:flex;justify-content:space-between;text-transform:uppercase;font-weight:600}.ui9 table{width:100%;border-collapse:collapse;font-size:13px}.ui9 th{padding:14px 0;text-align:left;font-size:10px;letter-spacing:4px;text-transform:uppercase;border-bottom:1px solid #0a0a0a;font-weight:700}.ui9 td{padding:20px 0;border-bottom:1px solid #e5e5e5}.ui9 .total{text-align:right;font-size:42px;font-weight:200;letter-spacing:1px;margin-top:20px;color:#0a0a0a}",
     'html': '<div class="ui9"><h1>INVOICE</h1><div class="ct"><span>{{ company }}</span><span>{{ invoice_no }} · {{ date }}</span></div><div style="font-size:13px">Bill to: <strong>{{ client }}</strong>, {{ client_address }}</div><table><tr><th>Description</th><th>Qty</th><th>Rate</th><th style="text-align:right">Total</th></tr>{% for it in items %}<tr><td>{{ it.desc }}</td><td>{{ it.qty }}</td><td>₹{{ it.price }}</td><td style="text-align:right">₹{{ it.total }}</td></tr>{% endfor %}</table><div class="total">₹{{ total }}</div><div style="margin-top:18px;font-size:11px;color:#737373;letter-spacing:1px">{{ notes }}</div></div>'},

    {'title': '💎 Marrakech Terracotta', 'desc': 'Warm terracotta artisanal with sun-baked palette.',
     'css': ".ui10{font-family:'Inter',sans-serif;max-width:780px;margin:0 auto;background:#fdf4ed;color:#3d1f0d;padding:60px 60px;border-top:8px solid #c4501d;box-shadow:0 50px 100px -20px rgba(196,80,29,.3)}.ui10 h1{font-family:'Playfair Display',serif;font-size:54px;color:#7a2e0f;margin:0;font-weight:500;font-style:italic}.ui10 .label{font-size:11px;letter-spacing:5px;color:#c4501d;text-transform:uppercase;font-weight:700;margin-bottom:8px}.ui10 table{width:100%;border-collapse:collapse;font-size:13px;margin-top:20px}.ui10 th{padding:14px;text-align:left;border-bottom:2px solid #c4501d;color:#c4501d;font-size:10px;letter-spacing:3px;text-transform:uppercase;font-weight:700}.ui10 td{padding:18px 14px;border-bottom:1px solid #f3d4ba}.ui10 .total{text-align:right;font-family:'Playfair Display',serif;font-size:42px;color:#c4501d;margin-top:20px;font-style:italic;font-weight:500}",
     'html': '<div class="ui10"><div class="label">— INVOICE —</div><h1>{{ company }}</h1><div style="display:flex;justify-content:space-between;font-size:13px;margin-top:18px"><div>{{ company_address }}<br>To: {{ client }}</div><div style="text-align:right">{{ invoice_no }}<br>{{ date }}</div></div><table><tr><th>Item</th><th>Qty</th><th>Rate</th><th>Total</th></tr>{% for it in items %}<tr><td>{{ it.desc }}</td><td>{{ it.qty }}</td><td>₹{{ it.price }}</td><td>₹{{ it.total }}</td></tr>{% endfor %}</table><div class="total">₹{{ total }}</div><div style="margin-top:18px;font-size:12px;color:#7a2e0f">{{ notes }}</div></div>'},
]


# ============================================================
# CARD — 10 LUXURY DESIGNS
# ============================================================
ULTRA_CARDS = [
    {'title': '💎 Onyx Foil Stamp', 'desc': 'Premium black with embossed gold foil monogram.',
     'css': ".uc1{width:380px;height:220px;background:#0a0a0a;color:#fff;padding:30px 26px;font-family:'Inter',sans-serif;margin:30px auto;border:1px solid #d4af37;outline:6px solid #0a0a0a;outline-offset:-12px;box-shadow:0 30px 70px rgba(0,0,0,.5),inset 0 0 30px rgba(212,175,55,.1);position:relative}.uc1::before{content:'';position:absolute;inset:14px;border:1px solid rgba(212,175,55,.3);pointer-events:none}.uc1 .mono{position:absolute;top:24px;right:26px;width:42px;height:42px;border:1.5px solid #d4af37;border-radius:50%;display:flex;align-items:center;justify-content:center;font-family:'Playfair Display',serif;color:#d4af37;font-size:20px;font-style:italic}.uc1 h2{font-family:'Playfair Display',serif;font-size:26px;margin:0;color:#fff;font-weight:300;letter-spacing:1px}.uc1 .role{font-size:9px;letter-spacing:5px;color:#d4af37;text-transform:uppercase;margin:8px 0 16px;font-weight:600}.uc1 .ct{font-size:10px;color:#a3a3a3;line-height:1.9;letter-spacing:.5px}",
     'html': '<div class="uc1"><div class="mono">{{ name|first }}</div><h2>{{ name }}</h2><div class="role">{{ title }} · {{ company }}</div><div class="ct">{{ email }}<br>{{ phone }}<br>{{ website }}</div></div>'},

    {'title': '💎 Champagne Letterpress', 'desc': 'Cream letterpress with serif elegance.',
     'css': ".uc2{width:380px;height:220px;background:#fef9ec;color:#1a1a1a;padding:30px 26px;font-family:'Cormorant Garamond',Georgia,serif;margin:30px auto;border:1px solid #d4af37;outline:4px solid #fef9ec;outline-offset:-10px;box-shadow:0 30px 70px rgba(212,175,55,.25);position:relative}.uc2::after{content:'';position:absolute;top:0;left:0;width:5px;height:100%;background:linear-gradient(180deg,#d4af37,#f5d28a)}.uc2 .label{font-family:'Inter',sans-serif;font-size:9px;letter-spacing:5px;color:#a8825c;text-transform:uppercase;font-weight:600}.uc2 h2{font-size:30px;margin:8px 0 4px;font-weight:500;line-height:1;font-style:italic}.uc2 .role{font-style:italic;color:#a8825c;font-size:13px;margin-bottom:14px;font-family:'Inter',sans-serif;letter-spacing:1px}.uc2 .ct{font-family:'Inter',sans-serif;font-size:10px;color:#737373;line-height:1.9;border-top:1px solid #d4af37;padding-top:10px}",
     'html': '<div class="uc2"><div class="label">— BUSINESS —</div><h2>{{ name }}</h2><div class="role">{{ title }} · {{ company }}</div><div class="ct">{{ email }}<br>{{ phone }} · {{ website }}</div></div>'},

    {'title': '💎 Monaco Navy Trim', 'desc': 'Royal navy with metallic gold trim stripe.',
     'css': ".uc3{width:380px;height:220px;background:linear-gradient(135deg,#0f1c3f,#1a2a52);color:#fff;padding:30px 26px;font-family:'Inter',sans-serif;margin:30px auto;border-radius:6px;box-shadow:0 30px 70px rgba(15,28,63,.5);position:relative;overflow:hidden}.uc3::before{content:'';position:absolute;left:0;top:0;width:6px;height:100%;background:linear-gradient(180deg,#d4af37,#f5d28a,#d4af37)}.uc3 h2{font-family:'Playfair Display',serif;font-size:26px;margin:0;color:#d4af37;font-weight:400;letter-spacing:.5px}.uc3 .role{color:#d4af37;font-size:9px;letter-spacing:4px;text-transform:uppercase;margin:6px 0 14px;font-weight:600;opacity:.9}.uc3 .company{font-size:13px;color:#fff;font-weight:600;margin-bottom:12px}.uc3 .ct{font-size:10px;color:#cbd5e1;line-height:1.9}",
     'html': '<div class="uc3"><h2>{{ name }}</h2><div class="role">{{ title }}</div><div class="company">{{ company }}</div><div class="ct">{{ email }}<br>{{ phone }}<br>{{ website }}</div></div>'},

    {'title': '💎 Vienna Burgundy Crest', 'desc': 'Heritage burgundy with double-rule borders.',
     'css': ".uc4{width:380px;height:220px;background:#fdfaf5;color:#2a1410;padding:30px 26px;font-family:'Cormorant Garamond',Georgia,serif;margin:30px auto;border-top:6px solid #6b1d2c;border-bottom:6px solid #6b1d2c;position:relative;box-shadow:0 30px 70px rgba(107,29,44,.25)}.uc4::before,.uc4::after{content:'';position:absolute;left:0;right:0;height:1px;background:#d4af37}.uc4::before{top:6px}.uc4::after{bottom:6px}.uc4 h2{font-size:28px;color:#6b1d2c;margin:0;font-weight:500;text-align:center;font-style:italic}.uc4 .role{text-align:center;font-style:italic;color:#8a4a52;font-size:12px;margin:6px 0 14px;font-family:'Inter',sans-serif;letter-spacing:1px;text-transform:uppercase;font-weight:600}.uc4 .ct{font-family:'Inter',sans-serif;font-size:10px;text-align:center;color:#737373;line-height:1.9}",
     'html': '<div class="uc4"><h2>{{ name }}</h2><div class="role">{{ title }} · {{ company }}</div><div class="ct">{{ email }}<br>{{ phone }} · {{ website }}</div></div>'},

    {'title': '💎 Tokyo Mono Refined', 'desc': 'Refined minimal mono card with red accent.',
     'css': ".uc5{width:380px;height:220px;background:#fafafa;color:#0a0a0a;padding:30px 26px;font-family:'Inter',sans-serif;margin:30px auto;border:1px solid #e5e5e5;position:relative;box-shadow:0 30px 70px rgba(0,0,0,.12)}.uc5 .hash{position:absolute;top:14px;right:14px;font-family:'Consolas',monospace;font-size:9px;color:#dc2626;letter-spacing:1px;font-weight:700}.uc5 h2{font-size:26px;margin:14px 0 4px;font-weight:200;letter-spacing:-.5px}.uc5 .role{font-size:9px;letter-spacing:4px;color:#525252;text-transform:uppercase;margin-bottom:14px;font-weight:600}.uc5 .line{width:32px;height:2px;background:#dc2626;margin:6px 0 14px}.uc5 .ct{font-family:'Consolas',monospace;font-size:10px;color:#525252;line-height:1.9}",
     'html': '<div class="uc5"><div class="hash">// 001</div><h2>{{ name }}</h2><div class="role">{{ title }} · {{ company }}</div><div class="line"></div><div class="ct">{{ email }}<br>{{ phone }}<br>{{ website }}</div></div>'},

    {'title': '💎 Milano Emerald Lux', 'desc': 'Emerald gradient with gold trim.',
     'css': ".uc6{width:380px;height:220px;background:linear-gradient(135deg,#064e3b,#0d3a2d);color:#fff;padding:30px 26px;font-family:'Inter',sans-serif;margin:30px auto;border-radius:8px;box-shadow:0 30px 70px rgba(6,78,59,.5);position:relative;overflow:hidden}.uc6::after{content:'';position:absolute;bottom:0;left:0;right:0;height:5px;background:linear-gradient(90deg,#d4af37,#f5d28a,#d4af37)}.uc6 h2{font-family:'Playfair Display',serif;font-size:28px;margin:0;color:#d4af37;font-weight:400;font-style:italic}.uc6 .role{color:#a7f3d0;font-size:10px;letter-spacing:3px;margin:6px 0 14px;text-transform:uppercase;font-weight:600}.uc6 .ct{font-size:10px;color:#a7f3d0;line-height:1.9}",
     'html': '<div class="uc6"><h2>{{ name }}</h2><div class="role">{{ title }} · {{ company }}</div><div class="ct">{{ email }}<br>{{ phone }} · {{ website }}</div></div>'},

    {'title': '💎 Park Avenue Slate', 'desc': 'Slate split-pane with monogram badge.',
     'css': ".uc7{width:380px;height:220px;background:#fff;color:#0f172a;font-family:'Inter',sans-serif;margin:30px auto;display:flex;border-radius:8px;overflow:hidden;box-shadow:0 30px 70px rgba(15,23,42,.25)}.uc7 .l{width:38%;background:#0f172a;color:#fbbf24;display:flex;align-items:center;justify-content:center;font-family:'Playfair Display',serif;font-size:60px;font-weight:300;font-style:italic}.uc7 .r{flex:1;padding:24px}.uc7 .r h2{font-family:'Playfair Display',serif;font-size:24px;margin:0;color:#0f172a;font-weight:500}.uc7 .r .role{font-size:9px;letter-spacing:3px;color:#fbbf24;margin:6px 0 12px;text-transform:uppercase;font-weight:700}.uc7 .r .ct{font-size:10px;color:#475569;line-height:1.9}",
     'html': '<div class="uc7"><div class="l">{{ name|first }}</div><div class="r"><h2>{{ name }}</h2><div class="role">{{ title }} · {{ company }}</div><div class="ct">{{ email }}<br>{{ phone }}<br>{{ website }}</div></div></div>'},

    {'title': '💎 Soho Pink Couture', 'desc': 'Couture pink with italic flair.',
     'css': ".uc8{width:380px;height:220px;background:linear-gradient(135deg,#fdf2f8,#fce7f3);color:#9d174d;padding:30px 26px;font-family:'Inter',sans-serif;margin:30px auto;border-radius:14px;border:2px solid #ec4899;box-shadow:0 30px 70px rgba(236,72,153,.25);position:relative;overflow:hidden}.uc8::before{content:'';position:absolute;top:0;left:0;right:0;height:5px;background:linear-gradient(90deg,#ec4899,#f97316,#ec4899)}.uc8 h2{font-family:'Playfair Display',serif;font-size:30px;margin:8px 0 0;font-style:italic;color:#9d174d;font-weight:500}.uc8 .role{font-size:9px;letter-spacing:4px;color:#ec4899;margin:6px 0 14px;text-transform:uppercase;font-weight:700}.uc8 .ct{font-size:10px;color:#9d174d;line-height:1.9}",
     'html': '<div class="uc8"><h2>{{ name }}</h2><div class="role">{{ title }} · {{ company }}</div><div class="ct">{{ email }}<br>{{ phone }} · {{ website }}</div></div>'},

    {'title': '💎 Geneva White Glove', 'desc': 'Ultra-minimal white with hairline border.',
     'css': ".uc9{width:380px;height:220px;background:#fff;color:#0a0a0a;padding:34px 28px;font-family:'Inter',sans-serif;margin:30px auto;border:1px solid #0a0a0a;display:flex;flex-direction:column;justify-content:space-between;box-shadow:0 30px 70px rgba(0,0,0,.12)}.uc9 h2{font-size:24px;margin:0;font-weight:200;letter-spacing:1.5px}.uc9 .role{font-size:9px;letter-spacing:6px;color:#525252;text-transform:uppercase;margin:8px 0;font-weight:600}.uc9 .line{width:30px;height:1px;background:#0a0a0a;margin:10px 0}.uc9 .ct{font-size:9px;letter-spacing:1px;color:#525252;line-height:2}",
     'html': '<div class="uc9"><div><h2>{{ name }}</h2><div class="role">{{ title }} · {{ company }}</div><div class="line"></div></div><div class="ct">{{ email }}<br>{{ phone }}<br>{{ website }}</div></div>'},

    {'title': '💎 Marrakech Terracotta', 'desc': 'Warm terracotta artisanal.',
     'css': ".uc10{width:380px;height:220px;background:#fdf4ed;color:#3d1f0d;padding:30px 26px;font-family:'Inter',sans-serif;margin:30px auto;border-top:6px solid #c4501d;box-shadow:0 30px 70px rgba(196,80,29,.25)}.uc10 h2{font-family:'Playfair Display',serif;font-size:28px;color:#7a2e0f;margin:0;font-weight:500;font-style:italic}.uc10 .role{color:#c4501d;font-size:11px;letter-spacing:2px;text-transform:uppercase;margin:6px 0 14px;font-weight:700}.uc10 .ct{font-size:10px;color:#7a2e0f;line-height:1.9}",
     'html': '<div class="uc10"><h2>{{ name }}</h2><div class="role">{{ title }} · {{ company }}</div><div class="ct">{{ email }}<br>{{ phone }} · {{ website }}</div></div>'},
]


# ============================================================
# CERTIFICATE — 10 LUXURY DESIGNS
# ============================================================
ULTRA_CERTIFICATES = [
    {'title': '💎 Maison Black Gold Honor', 'desc': 'Editorial luxury black with gold ornate border.',
     'css': ".ucr1{width:780px;margin:30px auto;background:#0a0a0a;color:#fff;padding:60px 50px;text-align:center;font-family:'Inter',sans-serif;border:2px solid #d4af37;outline:8px solid #0a0a0a;outline-offset:-16px;box-shadow:0 50px 100px -20px rgba(0,0,0,.6),inset 0 0 80px rgba(212,175,55,.05)}.ucr1 .deco{font-size:24px;color:#d4af37;letter-spacing:14px}.ucr1 .label{font-size:11px;letter-spacing:8px;color:#d4af37;text-transform:uppercase;margin:8px 0;font-weight:700}.ucr1 h1{font-family:'Playfair Display',serif;font-size:60px;margin:14px 0;color:#fff;letter-spacing:4px;font-weight:300}.ucr1 .pres{font-family:'Cormorant Garamond',serif;font-size:14px;color:#a3a3a3;font-style:italic;margin:14px 0}.ucr1 .name{font-family:'Playfair Display',serif;font-size:48px;color:#d4af37;font-style:italic;margin:14px 0;border-bottom:1px solid #d4af37;display:inline-block;padding:0 30px 8px;font-weight:400}.ucr1 .desc{font-family:'Cormorant Garamond',serif;font-size:15px;color:#cbcbcb;line-height:1.8;margin:14px 60px;font-style:italic}.ucr1 .course{font-family:'Playfair Display',serif;font-size:26px;color:#d4af37;margin:14px 0;font-style:italic}.ucr1 .footer{display:flex;justify-content:space-between;margin-top:40px;font-size:11px;color:#a3a3a3;letter-spacing:1px}.ucr1 .footer div{border-top:1px solid #d4af37;padding-top:8px;width:200px;text-transform:uppercase;font-weight:600}",
     'html': '<div class="ucr1"><div class="deco">❦ ❦ ❦</div><div class="label">— CERTIFICATE OF EXCELLENCE —</div><h1>HONOR</h1><div class="pres">This certificate is proudly presented to</div><div class="name">{{ recipient }}</div><div class="desc">{{ description }}</div><div class="course">{{ course }}</div><div class="footer"><div>{{ date }}</div><div>{{ signer }} · {{ title }}</div></div></div>'},

    {'title': '💎 Cream Editorial Diploma', 'desc': 'Magazine cream with ornate borders.',
     'css': ".ucr2{width:780px;margin:30px auto;background:#fef9ec;color:#1a1a1a;padding:60px 50px;text-align:center;font-family:'Cormorant Garamond',Georgia,serif;border:1px solid #d4af37;outline:6px solid #fef9ec;outline-offset:-14px;box-shadow:0 50px 100px -20px rgba(212,175,55,.3)}.ucr2 .deco{font-size:24px;color:#d4af37;letter-spacing:14px}.ucr2 .label{font-family:'Inter',sans-serif;font-size:11px;letter-spacing:8px;color:#a8825c;text-transform:uppercase;margin:8px 0;font-weight:700}.ucr2 h1{font-size:62px;margin:14px 0;font-weight:500;letter-spacing:3px;font-style:italic}.ucr2 .pres{font-style:italic;color:#737373;font-size:15px;margin:14px 0}.ucr2 .name{font-size:54px;margin:14px 0;color:#a8825c;font-weight:500;font-style:italic}.ucr2 .desc{font-family:'Inter',sans-serif;font-size:14px;color:#737373;line-height:1.8;margin:14px 60px;font-style:italic}.ucr2 .course{font-size:30px;color:#1a1a1a;margin:14px 0;font-style:italic;font-weight:500}.ucr2 .footer{display:flex;justify-content:space-between;margin-top:40px;font-size:12px;font-family:'Inter',sans-serif}.ucr2 .footer div{border-top:1px solid #a8825c;padding-top:8px;width:200px;text-transform:uppercase;font-weight:600;letter-spacing:1px;color:#a8825c}",
     'html': '<div class="ucr2"><div class="deco">⚜ ⚜ ⚜</div><div class="label">— CERTIFICATE OF ACHIEVEMENT —</div><h1>EXCELLENCE</h1><div class="pres">awarded to</div><div class="name">{{ recipient }}</div><div class="desc">{{ description }}</div><div class="course">{{ course }}</div><div class="footer"><div>{{ date }}</div><div>{{ signer }} · {{ title }}</div></div></div>'},

    {'title': '💎 Monaco Navy Royal Diploma', 'desc': 'Navy & gold royal diploma.',
     'css': ".ucr3{width:780px;margin:30px auto;background:#fff;font-family:'Inter',sans-serif;text-align:center;box-shadow:0 50px 100px -20px rgba(15,28,63,.3);border:1px solid #d4af37;position:relative}.ucr3 .top{background:linear-gradient(135deg,#0f1c3f 0%,#1a2a52 100%);color:#fff;padding:36px 50px;border-bottom:6px solid #d4af37;position:relative}.ucr3 .top::after{content:'';position:absolute;left:0;right:0;bottom:-6px;height:1px;background:#fff}.ucr3 .label{font-size:11px;letter-spacing:8px;color:#d4af37;text-transform:uppercase;font-weight:700}.ucr3 .top h1{font-family:'Playfair Display',serif;font-size:54px;margin:8px 0 0;color:#d4af37;font-weight:400;letter-spacing:3px}.ucr3 .body{padding:50px 60px}.ucr3 .pres{color:#737373;font-size:14px;font-style:italic;font-family:'Cormorant Garamond',serif}.ucr3 .name{font-family:'Playfair Display',serif;font-size:54px;color:#0f1c3f;margin:14px 0;font-weight:500;font-style:italic}.ucr3 .desc{font-family:'Cormorant Garamond',serif;font-size:16px;color:#475569;line-height:1.8;margin:14px 60px;font-style:italic}.ucr3 .course{font-family:'Playfair Display',serif;font-size:30px;color:#d4af37;font-style:italic;margin:14px 0;font-weight:500}.ucr3 .footer{display:flex;justify-content:space-between;margin-top:30px;font-size:12px;color:#475569;letter-spacing:1px}.ucr3 .footer div{border-top:1px solid #0f1c3f;padding-top:8px;width:200px;text-transform:uppercase;font-weight:600}",
     'html': '<div class="ucr3"><div class="top"><div class="label">CERTIFICATE</div><h1>OF MERIT</h1></div><div class="body"><div class="pres">This certificate is proudly presented to</div><div class="name">{{ recipient }}</div><div class="desc">{{ description }}</div><div class="course">{{ course }}</div><div class="footer"><div>{{ date }}</div><div>{{ signer }}<br>{{ title }}</div></div></div></div>'},

    {'title': '💎 Vienna Burgundy Royal', 'desc': 'Old-world burgundy royal certificate.',
     'css': ".ucr4{width:780px;margin:30px auto;background:#fdfaf5;color:#2a1410;padding:60px 50px;text-align:center;font-family:'Cormorant Garamond',Georgia,serif;border:8px double #6b1d2c;box-shadow:0 50px 100px -20px rgba(107,29,44,.3)}.ucr4 .deco{font-size:30px;color:#6b1d2c;letter-spacing:14px;margin-bottom:8px}.ucr4 .label{font-family:'Inter',sans-serif;font-size:12px;letter-spacing:8px;color:#8a4a52;text-transform:uppercase;font-weight:600}.ucr4 h1{font-size:60px;margin:14px 0;color:#6b1d2c;font-weight:500;letter-spacing:3px;font-style:italic}.ucr4 .name{font-size:54px;font-style:italic;color:#6b1d2c;margin:14px 0;font-weight:500}.ucr4 .desc{font-family:'Inter',sans-serif;font-size:14px;font-style:italic;color:#737373;line-height:1.8;margin:14px 60px}.ucr4 .course{font-size:30px;color:#8a4a52;margin:14px 0;font-style:italic;font-weight:500}.ucr4 .footer{display:flex;justify-content:space-between;margin-top:40px;font-size:12px;font-family:'Inter',sans-serif}.ucr4 .footer div{border-top:1px solid #6b1d2c;padding-top:8px;width:200px;text-transform:uppercase;font-weight:600;letter-spacing:1px;color:#6b1d2c}",
     'html': '<div class="ucr4"><div class="deco">⚜ ⚜ ⚜</div><div class="label">— Certificate —</div><h1>OF DISTINCTION</h1><div class="name">{{ recipient }}</div><div class="desc">{{ description }}</div><div class="course">{{ course }}</div><div class="footer"><div>{{ date }}</div><div>{{ signer }}</div></div></div>'},

    {'title': '💎 Tokyo Mono Plus', 'desc': 'Refined tech-style certificate.',
     'css': ".ucr5{width:780px;margin:30px auto;background:#fafafa;color:#0a0a0a;padding:60px 50px;text-align:center;font-family:'Inter',sans-serif;border:1px solid #e5e5e5;box-shadow:0 50px 100px -20px rgba(0,0,0,.15)}.ucr5 .hash{font-family:'Consolas',monospace;font-size:11px;color:#a3a3a3;letter-spacing:2px}.ucr5 h1{font-size:54px;margin:14px 0;font-weight:200;letter-spacing:1px}.ucr5 .name{font-size:48px;margin:14px 0;font-weight:300;color:#dc2626}.ucr5 .desc{font-size:14px;color:#525252;line-height:1.8;margin:14px 60px}.ucr5 .course{font-size:28px;color:#0a0a0a;font-weight:600;margin:14px 0}.ucr5 .footer{display:flex;justify-content:space-between;margin-top:40px;font-family:'Consolas',monospace;font-size:11px;color:#525252;letter-spacing:1px}.ucr5 .footer div{border-top:1px solid #dc2626;padding-top:8px;width:200px}",
     'html': '<div class="ucr5"><div class="hash">// CERTIFICATE.001</div><h1>CERTIFICATE</h1><div class="hash">PROOF OF SKILL</div><div class="name">{{ recipient }}</div><div class="desc">{{ description }}</div><div class="course">{{ course }}</div><div class="footer"><div>{{ date }}</div><div>{{ signer }} · {{ title }}</div></div></div>'},

    {'title': '💎 Milano Emerald Honor', 'desc': 'Emerald & gold luxury honor.',
     'css': ".ucr6{width:780px;margin:30px auto;background:#fff;font-family:'Inter',sans-serif;text-align:center;box-shadow:0 50px 100px -20px rgba(6,78,59,.25)}.ucr6 .top{background:linear-gradient(135deg,#064e3b 0%,#0d3a2d 100%);color:#fff;padding:40px 50px;border-bottom:6px solid #d4af37;position:relative}.ucr6 .top::after{content:'';position:absolute;left:0;right:0;bottom:-6px;height:1px;background:#fff}.ucr6 .top h1{font-family:'Playfair Display',serif;font-size:54px;margin:0;color:#d4af37;font-weight:400;letter-spacing:4px;font-style:italic}.ucr6 .body{padding:50px 60px}.ucr6 .name{font-family:'Playfair Display',serif;font-size:54px;color:#064e3b;margin:14px 0;font-weight:500;font-style:italic;border-bottom:2px solid #d4af37;display:inline-block;padding:0 30px 8px}.ucr6 .desc{font-family:'Cormorant Garamond',serif;font-size:16px;color:#475569;line-height:1.8;margin:14px 60px;font-style:italic}.ucr6 .course{font-family:'Playfair Display',serif;font-size:30px;color:#064e3b;font-style:italic;font-weight:500}.ucr6 .footer{display:flex;justify-content:space-between;margin-top:30px;font-size:12px;color:#475569}.ucr6 .footer div{border-top:1px solid #064e3b;padding-top:8px;width:200px;text-transform:uppercase;font-weight:600;letter-spacing:1px}",
     'html': '<div class="ucr6"><div class="top"><h1>CERTIFICATE OF EXCELLENCE</h1></div><div class="body"><div style="font-style:italic;color:#737373;font-family:Cormorant Garamond,serif">awarded to</div><div class="name">{{ recipient }}</div><div class="desc">{{ description }}</div><div class="course">{{ course }}</div><div class="footer"><div>{{ date }}</div><div>{{ signer }}<br>{{ title }}</div></div></div></div>'},

    {'title': '💎 Park Avenue Slate', 'desc': 'Slate corporate excellence.',
     'css': ".ucr7{width:780px;margin:30px auto;background:#fff;color:#0f172a;padding:60px 50px;text-align:center;font-family:'Inter',sans-serif;border-top:14px solid #0f172a;border-bottom:14px solid #fbbf24;box-shadow:0 50px 100px -20px rgba(15,23,42,.2)}.ucr7 .label{font-size:11px;letter-spacing:8px;color:#fbbf24;text-transform:uppercase;font-weight:700}.ucr7 h1{font-family:'Playfair Display',serif;font-size:56px;margin:14px 0;color:#0f172a;font-weight:500;font-style:italic}.ucr7 .name{font-family:'Playfair Display',serif;font-size:54px;color:#fbbf24;margin:14px 0;font-style:italic;font-weight:500}.ucr7 .desc{font-family:'Cormorant Garamond',serif;font-size:16px;color:#475569;line-height:1.8;margin:14px 60px;font-style:italic}.ucr7 .course{font-size:28px;color:#0f172a;font-weight:600;margin:14px 0}.ucr7 .footer{display:flex;justify-content:space-between;margin-top:40px;font-size:12px;color:#475569}.ucr7 .footer div{border-top:2px solid #0f172a;padding-top:8px;width:200px;text-transform:uppercase;font-weight:700;letter-spacing:1px}",
     'html': '<div class="ucr7"><div class="label">— CORPORATE EXCELLENCE —</div><h1>EMPLOYEE OF THE YEAR</h1><div class="name">{{ recipient }}</div><div class="desc">{{ description }}</div><div class="course">{{ course }}</div><div class="footer"><div>{{ date }}</div><div>{{ signer }} · {{ title }}</div></div></div>'},

    {'title': '💎 Soho Pink Couture', 'desc': 'Couture pink merit certificate.',
     'css': ".ucr8{width:780px;margin:30px auto;background:#fef6f3;color:#1a1a1a;padding:60px 50px;text-align:center;font-family:'Inter',sans-serif;border:3px solid #ec4899;border-radius:18px;position:relative;box-shadow:0 50px 100px -20px rgba(236,72,153,.25)}.ucr8::before{content:'';position:absolute;top:0;left:0;right:0;height:8px;background:linear-gradient(90deg,#ec4899,#f97316,#ec4899)}.ucr8 .label{font-size:11px;letter-spacing:6px;color:#ec4899;text-transform:uppercase;font-weight:700}.ucr8 h1{font-family:'Playfair Display',serif;font-size:56px;margin:14px 0;font-style:italic;color:#9d174d;font-weight:500}.ucr8 .name{font-family:'Playfair Display',serif;font-size:54px;color:#ec4899;margin:14px 0;font-style:italic;font-weight:500}.ucr8 .desc{font-family:'Cormorant Garamond',serif;font-size:16px;color:#737373;line-height:1.8;margin:14px 60px;font-style:italic}.ucr8 .course{font-family:'Playfair Display',serif;font-size:30px;color:#9d174d;font-style:italic;font-weight:500}.ucr8 .footer{display:flex;justify-content:space-between;margin-top:30px;font-size:12px;color:#737373}.ucr8 .footer div{border-top:1px solid #ec4899;padding-top:8px;width:200px;text-transform:uppercase;font-weight:600;letter-spacing:1px}",
     'html': '<div class="ucr8"><div class="label">— CERTIFICATE OF APPRECIATION —</div><h1>Recognition</h1><div class="name">{{ recipient }}</div><div class="desc">{{ description }}</div><div class="course">{{ course }}</div><div class="footer"><div>{{ date }}</div><div>{{ signer }}</div></div></div>'},

    {'title': '💎 Geneva Pristine', 'desc': 'Ultra-minimal white-glove certificate.',
     'css': ".ucr9{width:780px;margin:30px auto;background:#fff;color:#0a0a0a;padding:90px 70px;text-align:center;font-family:'Inter',sans-serif;border:1px solid #0a0a0a;box-shadow:0 50px 100px -20px rgba(0,0,0,.15)}.ucr9 .label{font-size:11px;letter-spacing:10px;text-transform:uppercase;font-weight:700}.ucr9 h1{font-size:50px;margin:24px 0;font-weight:200;letter-spacing:4px}.ucr9 .line{width:100px;height:1px;background:#0a0a0a;margin:30px auto}.ucr9 .name{font-size:46px;margin:14px 0;font-weight:300;letter-spacing:1px}.ucr9 .desc{font-size:13px;color:#525252;line-height:2;margin:14px 80px;font-style:italic}.ucr9 .course{font-size:28px;font-weight:400;color:#0a0a0a;margin:14px 0}.ucr9 .footer{display:flex;justify-content:space-between;margin-top:60px;font-size:10px;letter-spacing:3px;color:#525252;text-transform:uppercase;font-weight:600}.ucr9 .footer div{border-top:1px solid #0a0a0a;padding-top:8px;width:200px}",
     'html': '<div class="ucr9"><div class="label">CERTIFICATE</div><h1>OF ACHIEVEMENT</h1><div class="line"></div><div class="name">{{ recipient }}</div><div class="desc">{{ description }}</div><div class="course">{{ course }}</div><div class="footer"><div>{{ date }}</div><div>{{ signer }} · {{ title }}</div></div></div>'},

    {'title': '💎 Marrakech Terracotta', 'desc': 'Warm terracotta artisanal certificate.',
     'css': ".ucr10{width:780px;margin:30px auto;background:#fdf4ed;color:#3d1f0d;padding:60px 50px;text-align:center;font-family:'Inter',sans-serif;border:8px double #c4501d;border-radius:8px;box-shadow:0 50px 100px -20px rgba(196,80,29,.3)}.ucr10 .label{font-size:11px;letter-spacing:6px;color:#c4501d;text-transform:uppercase;font-weight:700}.ucr10 h1{font-family:'Playfair Display',serif;font-size:56px;color:#7a2e0f;margin:14px 0;font-weight:500;font-style:italic}.ucr10 .name{font-family:'Playfair Display',serif;font-size:54px;color:#c4501d;margin:14px 0;font-style:italic;font-weight:500}.ucr10 .desc{font-family:'Cormorant Garamond',serif;font-size:16px;color:#7a2e0f;line-height:1.8;margin:14px 60px;font-style:italic}.ucr10 .course{font-family:'Playfair Display',serif;font-size:28px;color:#c4501d;font-style:italic;font-weight:500}.ucr10 .footer{display:flex;justify-content:space-between;margin-top:30px;font-size:12px;color:#7a2e0f}.ucr10 .footer div{border-top:1px solid #c4501d;padding-top:8px;width:200px;text-transform:uppercase;font-weight:600;letter-spacing:1px}",
     'html': '<div class="ucr10"><div class="label">— CERTIFICATE OF MERIT —</div><h1>EXCELLENCE</h1><div class="name">{{ recipient }}</div><div class="desc">{{ description }}</div><div class="course">{{ course }}</div><div class="footer"><div>{{ date }}</div><div>{{ signer }} · {{ title }}</div></div></div>'},
]
